### PR TITLE
Fix inline evaluation result not displaying

### LINKED ISSUE #1332: Inline evaluation results no longer display in 2.0.216
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

### PR DESCRIPTION
**Pull request by S4G4R**
## What has Changed?

- Replace usage of `replaceAll` with `replace`

Fixes #1332 
Workaround for #1339 

## My Calva PR Checklist

I have:

- [x]  Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

### CODE REVIEW

File: src/custom-snippets.ts [hunk 1]
```diff
@@ -86,18 +86,18 @@ async function evaluateCustomCodeSnippet(codeOrKey?: string): Promise<void> {
...
+        replace("$file", currentFilename).
+        replace("$ns", ns).
+        replace("$selection", editor.document.getText(editor.selection)).
+        replace("$current-form", getText.currentFormText(editor)[1]).
+        replace("$enclosing-form", getText.currentEnclosingFormText(editor)[1]).
+        replace("$top-level-form", getText.currentTopLevelFormText(editor)[1]).
+        replace("$current-fn", getText.currentFunction(editor)[1]).
+        replace("$top-level-defined-symbol", getText.currentTopLevelFunction(editor)[1]).
+        replace("$head", getText.toStartOfList(editor)[1]).
+        replace("$tail", getText.toEndOfList(editor)[1]);
```
Comment (PEZ) [inline src/custom-snippets.ts]: This won't work, because it will only replace the first occurrence and will bring back #1301. It will need to be a regex and not a string so that we can add the `g` modifier. I think this should work (it needs to be tested).

```suggestion
        replace(/\$line/g, currentLine).
        replace(/\$column/g, currentColumn).
        replace(/\$file/g, currentFilename).
        replace(/\$ns/g, ns).
        replace(/\$selection/g, editor.document.getText(editor.selection)).
        replace(/\$current-form/g, getText.currentFormText(editor)[1]).
        replace(/\$enclosing-form/g, getText.currentEnclosingFormText(editor)[1]).
        replace(/\$top-level-form/g, getText.currentTopLevelFormText(editor)[1]).
        replace(/\$current-fn/g, getText.currentFunction(editor)[1]).
        replace(/\$top-level-defined-symbol/g, getText.currentTopLevelFunction(editor)[1]).
        replace(/\$head/g, getText.toStartOfList(editor)[1]).
        replace(/\$tail/g, getText.toEndOfList(editor)[1]);
 ```

**Review by PEZ — CHANGES_REQUESTED** [review]
Thanks! See my comment on custom snippets.

**Comment by PEZ** [comment]
Many thanks!
