### PR TITLE
Fix load file for Windows

### LINKED ISSUE #975: Load file command not loading changes since last file save on Windows
-> Running a changed test (also for the other test commands) requires the .clj file with the tests to be saved before the updated test is recognized

Repro steps:
> lein new app calva-test
Goto VSC and start the repl
"Run tests in current namespace" to run the default test
Changes the default test in core_test.clj (like change the 1 in a 2)
"Run tests in current namespace" to run the default test
-> test is still the old test

PS: The other command to run the test produce the same results.

As bringe indicated, a save should not be required.

----
dangercoder Yesterday at 3:38 PM
Does anyone else have issues with running tests through "Run tests in current namespace"? When I redefine my tests, calva doesn't understand that they have been updated.

8 replies

dangercoder  1 day ago
I also tried to reload the whole shebangs into the repl.
If I run the tests through the repl without Calva, things works fine though :slightly_smiling_face:

bringe  1 day ago
Please create an issue with repro steps. I've not experienced this myself, but maybe it's a particular case, or something has broken.
:+1:
1

Eric Uitbeijerse  24 hours ago
@dangercoder It still works fine for me, but I do have to save all the files after I update the tests (Ctrl-K S)

bringe  19 hours ago
It shouldn't require a file save, if it does there is a bug. For me, I can run a failing test, make it pass, not save the file, "run tests in current namespace" and it passes. (edited) 

Eric Uitbeijerse  12 hours ago
Would be nice if it does not require a file save, that would save some time. I'll have another look at it later on and report back.
:+1:
1

dangercoder  2 hours ago
Tests understands the updates when I save the file manually

dangercoder  2 hours ago
Thanks for the tip @Eric Uitbeijerse

bringe  1 hour ago
A save is not supposed to be necessary since the test command reloads the file, and is not necessary for me. An issue would be appreciated.

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Refactors load file to use a vscode.Uri instead of just string fileName and filePath

I tested these changes with all scenarios that I could tell might be effected, including loading current file with jar files and revealing the file for the current output window ns, including for jar files.

Fixes #975 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Added to or updated docs in this branch, if appropriate

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

File: src/evaluate.ts [hunk 1]
```diff
@@ -223,22 +223,21 @@ async function loadFile(document, pprintOptions: PrettyPrintingOptions) {
...
         outputWindow.append("; Evaluating file: " + fileName);
 
         await session.eval("(in-ns '" + ns + ")", session.client.ns).value;
 
         const res = session.loadFile(fileContents, {
-            fileName: fileName,
-            filePath,
-            stdout: m => outputWindow.append(normalizeNewLines(m.indexOf(dirName) < 0 ? m.replace(shortFileName, fileName) : m)),
-            stderr: m => outputWindow.append('; ' + normalizeNewLines(m.indexOf(dirName) < 0 ? m.replace(shortFileName, fileName) : m, true)),
+            fileName,
```
Comment (bpringe) [inline src/evaluate.ts:237]: From what I could see, `fileName` was always the same as `shortFileName`. I'm guessing this replacement code may be left from some other time when things were different. All works fine and as expected though when testing.

File: src/results-output/results-doc.ts [hunk 2]
```diff
@@ -362,9 +358,8 @@ export function appendPrompt(onAppended?: OnAppendedCallback) {
     append(getPrompt(), onAppended);
 }
 
-export async function getFilePathForCurrentNameSpace(): Promise<[string, string]> {
+export async function getUriForCurrentNamespace(): Promise<vscode.Uri> {
     const ns = getNs();
     const info = await getSession().info(ns, ns);
-    const fileName = info.file;
-    return [fileName, vscode.Uri.parse(fileName).path];
+    return vscode.Uri.parse(info.file, true);
```
Comment (bpringe) [inline src/results-output/results-doc.ts:364]: It seems more reliable to pass around a `vscode.Uri` for cross platform reasons, and pick what you need from it when needed.

**Review by PEZ — APPROVED** [review]
Superb stuff!
