### PR TITLE
2336 completion merge

### LINKED ISSUE #2336: Namespace alias shadows local variables
Bug discussed here: https://clojurians.slack.com/archives/CBE668G4R/p1699023626527349

Originaly reported by @brjann here: https://github.com/clojure-lsp/clojure-lsp/issues/1718

I'm using Calva. If a namespace alias shares name with a variable, argument or local binding, the autocompletion will only show the namespace alias. Hitting tab will add the aliased namespace as a dependency to the ns.

**To Reproduce**
```clojure
;; aliased.clj
(ns aliased)

;; aliasing.clj
(ns aliasing
  (:require [aliased :as ns-alias]))

;; another_ns.clj
(ns another-ns)

(def ns-alias 0)

(defn bar
  []
  (ns-a)) ;; Autocomplete will only suggest "ns-alias alias to: aliased" LSP-OUTPUT

(defn foo
  [ns-alias]
  (ns-a)) ;; Autocomplete will only suggest "ns-alias alias to: aliased" 

(defn baz
  []
  (let [ns-alias 0]
    ns-a)) ;; Autocomplete will only suggest "ns-alias alias to: aliased" 
````

**Expected behavior**
In the cases above, the var, argument, and local binding, respectively, should be (1) suggested, and (2) the first suggestions in the autocompletion.

The Clojure LSP output below is for when I type l on the "LSP-OUTPUT" line

<details>
<summary>clojure-lsp output</summary>

```
[Trace - 17:03:56] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///src/clj/another_ns.clj",
        "version": 141
    },
    "contentChanges": [
        {
            "text": "(ns another-ns)\n\n(def ns-alias 0)\n\n(defn bar\n  []\n  (ns-a)) ;; Autocomplete will only suggest \"ns-alias alias to: aliased\" \n\n(defn foo\n  [ns-alias]\n  (ns-a)) ;; Autocomplete will only suggest \"ns-alias alias to: aliased\" \n\n(defn baz\n  []\n  (let [ns-alias 0]\n    ns-a)) ;; Autocomplete will only suggest \"ns-alias alias to: aliased\" "
        }
    ]
}
[Trace - 17:03:56] Sending request 'textDocument/completion - (6525)'.

Params: {

"textDocument": {

"uri": "file:///src/clj/another_ns.clj"

},

"position": {

"line": 6,

"character": 7

},

"context": {

"triggerKind": 1

}

}


[Trace - 17:03:56] Received response 'textDocument/completion - (6525)' in 21ms.

Result: [

{

"label": "ns-alias",

"kind": 6,

"data": {

"unresolved": [

[

"documentation",

{

"name": "ns-alias",

"uri": "file:///src/clj/another_ns.clj",

"name-row": 3,

"name-col": 6

}

]

]

},

"score": 14

},

{

"label": "ns-alias",

"kind": 10,

"detail": "alias to: aliased",

"data": {

"unresolved": [

[

"alias",

{

"ns-to-add": "aliased",

"alias-to-add": "ns-alias",

"uri": "file:///src/clj/another_ns.clj"

}

]

]

},

"score": 9

},

{

"label": "ns-aliases",

"kind": 3,

"detail": "clojure.core/ns-aliases",

"data": {

"unresolved": [

[

"documentation",

{

"uri": "file:///clojure.core.clj",

"name": "ns-aliases",

"ns": "clojure.core"

}

]

]

},

"score": 6

}

]


[Trace - 17:03:56] Sending request 'completionItem/resolve - (6526)'.

Params: {

"label": "ns-alias",

"detail": "alias to: aliased",

"insertTextFormat": 1,

"kind": 10,

"data": {

"unresolved": [

[

"alias",

{

"ns-to-add": "aliased",

"alias-to-add": "ns-alias",

"uri": "file:///src/clj/another_ns.clj"

}

]

]

}

}


[Trace - 17:03:56] Received response 'completionItem/resolve - (6526)' in 1ms.

Result: {

"label": "ns-alias",

"detail": "alias to: aliased",

"insertTextFormat": 1,

"kind": 10,

"additionalTextEdits": [

{

"range": {

"start": {

"line": 0,

"character": 0

},

"end": {

"line": 0,

"character": 15

}

},

"newText": "(ns another-ns \n  (:require [aliased :as ns-alias]))"

}

]

}


[Trace - 17:03:56] Received notification 'textDocument/publishDiagnostics'.

Params: {

"uri": "file:///src/clj/another_ns.clj",

"diagnostics": [

{

"range": {

"start": {

"line": 2,

"character": 5

},

"end": {

"line": 2,

"character": 13

}

},

"tags": [

1

],

"message": "Unused public var 'another-ns/ns-alias'",

"code": "clojure-lsp/unused-public-var",

"langs": [],

"severity": 3,

"source": "clojure-lsp"

},

{

"range": {

"start": {

"line": 4,

"character": 6

},

"end": {

"line": 4,

"character": 9

}

},

"tags": [

1

],

"message": "Unused public var 'another-ns/bar'",

"code": "clojure-lsp/unused-public-var",

"langs": [],

"severity": 3,

"source": "clojure-lsp"

},

{

"range": {

"start": {

"line": 6,

"character": 3

},

"end": {

"line": 6,

"character": 7

}

},

"tags": [],

"message": "Unresolved symbol: ns-a",

"code": "unresolved-symbol",

"langs": [],

"severity": 1,

"source": "clj-kondo"

},

{

"range": {

"start": {

"line": 8,

"character": 6

},

"end": {

"line": 8,

"character": 9

}

},

"tags": [

1

],

"message": "Unused public var 'another-ns/foo'",

"code": "clojure-lsp/unused-public-var",

"langs": [],

"severity": 3,

"source": "clojure-lsp"

},

{

"range": {

"start": {

"line": 9,

"character": 3

},

"end": {

"line": 9,

"character": 11

}

},

"tags": [

1

],

"message": "unused binding ns-alias",

"code": "unused-binding",

"langs": [],

"severity": 2,

"source": "clj-kondo"

},

{

"range": {

"start": {

"line": 10,

"character": 3

},

"end": {

"line": 10,

"character": 7

}

},

"tags": [],

"message": "Unresolved symbol: ns-a",

"code": "unresolved-symbol",

"langs": [],

"severity": 1,

"source": "clj-kondo"

},

{

"range": {

"start": {

"line": 12,

"character": 6

},

"end": {

"line": 12,

"character": 9

}

},

"tags": [

1

],

"message": "Unused public var 'another-ns/baz'",

"code": "clojure-lsp/unused-public-var",

"langs": [],

"severity": 3,

"source": "clojure-lsp"

},

{

"range": {

"start": {

"line": 14,

"character": 8

},

"end": {

"line": 14,

"character": 16

}

},

"tags": [

1

],

"message": "unused binding ns-alias",

"code": "unused-binding",

"langs": [],

"severity": 2,

"source": "clj-kondo"

},

{

"range": {

"start": {

"line": 15,

"character": 4

},

"end": {

"line": 15,

"character": 8

}

},

"tags": [],

"message": "Unresolved symbol: ns-a",

"code": "unresolved-symbol",

"langs": [],

"severity": 1,

"source": "clj-kondo"

}

]

}


[Trace - 17:03:56] Sending request 'textDocument/codeAction - (6527)'.

Params: {

"textDocument": {

"uri": "file:///src/clj/another_ns.clj"

},

"range": {

"start": {

"line": 6,

"character": 7

},

"end": {

"line": 6,

"character": 7

}

},

"context": {

"diagnostics": [

{

"range": {

"start": {

"line": 6,

"character": 3

},

"end": {

"line": 6,

"character": 7

}

},

"message": "Unresolved symbol: ns-a",

"code": "unresolved-symbol",

"severity": 1,

"source": "clj-kondo"

}

],

"triggerKind": 2

}

}


[Trace - 17:03:56] Received response 'textDocument/codeAction - (6527)' in 48ms.

Result: [

{

"title": "Create private function 'ns-a'",

"kind": "quickfix",

"command": {

"title": "Create function",

"command": "create-function",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

3

]

}

},

{

"title": "Change coll to vector",

"kind": "refactor",

"command": {

"title": "Change coll",

"command": "change-coll",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"vector"

]

}

},

{

"title": "Change coll to set",

"kind": "refactor",

"command": {

"title": "Change coll",

"command": "change-coll",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"set"

]

}

},

{

"title": "Change coll to map",

"kind": "refactor",

"command": {

"title": "Change coll",

"command": "change-coll",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"map"

]

}

},

{

"title": "Move to let",

"kind": "refactor.extract",

"command": {

"title": "Move to let",

"command": "move-to-let",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"new-binding"

]

}

},

{

"title": "Cycle privacy",

"kind": "refactor.rewrite",

"command": {

"title": "Cycle privacy",

"command": "cycle-privacy",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Extract function",

"kind": "refactor.extract",

"command": {

"title": "Extract function",

"command": "extract-function",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"new-function"

]

}

},

{

"title": "Extract to def",

"kind": "refactor.extract",

"command": {

"title": "Extract to def",

"command": "extract-to-def",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

null

]

}

},

{

"title": "Thread first all",

"kind": "refactor.rewrite",

"command": {

"title": "Thread first all",

"command": "thread-first-all",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Thread last all",

"kind": "refactor.rewrite",

"command": {

"title": "Thread last all",

"command": "thread-last-all",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Sort list",

"kind": "refactor.rewrite",

"command": {

"title": "Sort list",

"command": "sort-clauses",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Drag backward",

"kind": "refactor.rewrite",

"command": {

"title": "Drag backward",

"command": "drag-backward",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Introduce let",

"kind": "refactor.extract",

"command": {

"title": "Introduce let",

"command": "introduce-let",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7,

"new-binding"

]

}

},

{

"title": "Suppress 'unresolved-symbol' diagnostic",

"kind": "quickfix",

"command": {

"title": "Suppress diagnostic",

"command": "suppress-diagnostic",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

3,

"unresolved-symbol"

]

}

},

{

"title": "Create test for 'bar'",

"kind": "refactor.rewrite",

"command": {

"title": "Create test",

"command": "create-test",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

},

{

"title": "Clean namespace",

"kind": "source.organizeImports",

"command": {

"title": "Clean namespace",

"command": "clean-ns",

"arguments": [

"file:///src/clj/another_ns.clj",

6,

7

]

}

}

]


[Trace - 17:03:56] Sending request 'textDocument/semanticTokens/full - (6528)'.

Params: {

"textDocument": {

"uri": "file:///src/clj/another_ns.clj"

}

}


[Trace - 17:03:56] Received response 'textDocument/semanticTokens/full - (6528)' in 1ms.

Result: {

"data": [

0,

4,

10,

0,

0,

2,

1,

3,

3,

0,

0,

4,

8,

2,

1,

2,

1,

4,

3,

0,

0,

5,

3,

2,

1,

4,

1,

4,

3,

0,

0,

5,

3,

2,

1,

1,

3,

8,

6,

0,

3,

1,

4,

3,

0,

0,

5,

3,

2,

1,

2,

3,

3,

3,

0,

0,

5,

8,

6,

0

]

}


[Trace - 17:03:56] Sending request 'textDocument/documentSymbol - (6529)'.

Params: {

"textDocument": {

"uri": "file:///src/clj/another_ns.clj"

}

}


[Trace - 17:03:56] Received response 'textDocument/documentSymbol - (6529)' in 2ms.

Result: [

{

"name": "another-ns",

"kind": 3,

"range": {

"start": {

"line": 0,

"character": 0

},

"end": {

"line": 999999,

"character": 999999

}

},

"selectionRange": {

"start": {

"line": 0,

"character": 0

},

"end": {

"line": 0,

"character": 15

}

},

"children": [

{

"name": "ns-alias",

"kind": 13,

"range": {

"start": {

"line": 2,

"character": 0

},

"end": {

"line": 2,

"character": 16

}

},

"selectionRange": {

"start": {

"line": 2,

"character": 5

},

"end": {

"line": 2,

"character": 13

}

},

"tags": []

},

{

"name": "bar",

"kind": 12,

"range": {

"start": {

"line": 4,

"character": 0

},

"end": {

"line": 6,

"character": 9

}

},

"selectionRange": {

"start": {

"line": 4,

"character": 6

},

"end": {

"line": 4,

"character": 9

}

},

"tags": []

},

{

"name": "foo",

"kind": 12,

"range": {

"start": {

"line": 8,

"character": 0

},

"end": {

"line": 10,

"character": 9

}

},

"selectionRange": {

"start": {

"line": 8,

"character": 6

},

"end": {

"line": 8,

"character": 9

}

},

"tags": []

},

{

"name": "baz",

"kind": 12,

"range": {

"start": {

"line": 12,

"character": 0

},

"end": {

"line": 15,

"character": 10

}

},

"selectionRange": {

"start": {

"line": 12,

"character": 6

},

"end": {

"line": 12,

"character": 9

}

},

"tags": []

}

]

}

]

```
</details>

### PR DESCRIPTION
**Pull request by PEZ**
## What has changed?

The merge of lsp and nrepl completion items wasn't working as we intended. So I fixed that and added some tests for it.

Also, while merging the LSP `CompletionItemKind`s are used, which are off by one from VS Code's. This made our mapping from nREPL completion `type`s off by one as well. I fixed that too. No tests here, though, as I think maybe the comment I added where I add one to the mappings is enough?

* Fixes #2336

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/providers/completion.ts [hunk 1]
```diff
@@ -62,18 +69,11 @@ async function provideCompletionItems(
     ).catch((err) => {
       console.log(`Failed to get results from completions provider '${provider}'`, err);
     });
-
+    console.log('completions', provider, completions);
+    console.log('results before merge', provider, results);
```
Comment (bpringe) [inline src/providers/completion.ts:73]: I'm thinking we want to clean these and some other log statements up.

Comment (PEZ) [reply src/providers/completion.ts:73]: I think I removed these particular logs the other day.
