### PR TITLE
cljfmt 11.0.x extra indents fix

### LINKED ISSUE #2280: Update the indenter to handle the cljfmt `0.11.x` breaking config update since version 2.0.383
From  https://github.com/weavejester/cljfmt/tree/master#breaking-changes-in-011x:

> The `:indents` key has been split into `:indents` and `:extra-indents`. The `:indents` key replaces all default indents, while the :`extra-indents` key will append to the default indents.

This probably should be mentioned in the Calva docs. Perhaps it calls for an update to the docs more generally to include the `:extra-indents`, since that is probably the most common configuration from now on.

It also calls for an update of how the Calva indenter reads the configuration. We probably need to recreate the logic now used in **cljfmt** for this, including the `:legacy/merge-indents?` escape hatch.

### PR DESCRIPTION
**Pull request by PEZ**
## What has changed?

* Makes the indenter read `:extra-indents` and `:indents` from the cljfmt configuration, and merge in cljfmt/default-indent:
    * if `:indents` is not used, or
    * if `:indents` are used and `:legacy/merge-indents?` is true.
* Fixes a bug with #2285 (not released yet) where the lack of an `:indent` map in the config made the indenter fail to parse the config completely.

This

* Fixes #2280 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/extension-test/unit/cursor-doc/indent-test.ts [hunk 1]
```diff
@@ -250,6 +250,24 @@ describe('indent', () => {
...
+      it('with empty replace config, does not use the built-in rule for the `let` body', () => {
+        expect(indent.getIndent(doc.model, p, emptyConfig)).toEqual(5);
+      });
+      const someConfig = mkConfig(
+        {
+          '/foo+/': [['inner', 0]],
+        },
+        {}
+      );
+      it('with some config, still uses the built-in the built-in rule for the `let` body', () => {
```
Comment (juiceghost) [inline src/extension-test/unit/cursor-doc/indent-test.ts:268]: Is the built-in doubled here unintentionally?

File: src/extension-test/unit/cursor-doc/indent-test.ts [hunk 2]
```diff
@@ -380,10 +398,13 @@ describe('indent', () => {
...
 });
 
-function mkConfig(rules: indent.IndentRules) {
+function mkConfig(extraRules: indent.IndentRules, replaceRules?: indent.IndentRules) {
   return {
     'cljfmt-options': {
-      indents: rules,
+      ...{
+        'extra-indents': extraRules,
+      },
```
Comment (juiceghost) [inline src/extension-test/unit/cursor-doc/indent-test.ts]: I think this destructuring of a single key/value pair inside an object could be superfluous?

So instead of
```
...{
        'extra-indents': extraRules,
      },
```
We should be fine with
`'extra-indents': extraRules,`

File: src/formatter-config.ts [hunk 3]
```diff
@@ -14,18 +14,8 @@ const defaultCljfmtContent =
...
-    ? options
-    : {
-        ...options,
-        indents: options['indents'],
-      };
-}
-
 function configuration(workspaceConfig: vscode.WorkspaceConfiguration, cljfmt: string) {
-  const cljfmtOptions = cljfmtOptionsFromString(cljfmt);
+  const cljfmtOptions = cljsLib.cljfmtOptionsFromString(cljfmt);
```
Comment (juiceghost) [inline src/formatter-config.ts:18]: Does this change mean that in case of error, we would get the defaultIndents rather than just the indents from options?

Looking at
```
(defn- read-cljfmt
  [s]
  (try
    (as-> s $
      (parse-clj-edn $))
    (catch js/Error e
      (merge default-fmt
             {:error (.-message e)
              :indents cljfmt/default-indents}))))
```

in formatter.cljs

File: src/extension-test/unit/cursor-doc/indent-test.ts (hunk 2 above)
Comment (PEZ) [reply src/extension-test/unit/cursor-doc/indent-test.ts]: Wouldn't that risk create a `'extra-indents': undefined` entry?

File: src/formatter-config.ts (hunk 3 above)
Comment (PEZ) [reply src/formatter-config.ts:18]: Yes. “just the indents from options” are not available if the parsing fails.

File: src/extension-test/unit/cursor-doc/indent-test.ts (hunk 2 above)
Comment (PEZ) [reply src/extension-test/unit/cursor-doc/indent-test.ts]: Ah, I see what you mean now. Fixed it. Thanks!
