### PR TITLE
Jack-in fails with version 2.0.337

### LINKED ISSUE #2113: Jack-in fails with version 2.0.337
Jack-in is not working anymore, Calva can't connect to nREPL server whereas it is correctly launched.

```
; This is the Calva evaluation results output window.
; TIPS: The keyboard shortcut `ctrl+alt+o o` shows and focuses this window
;   when connected to a REPL session.
; Please see https://calva.io/output/ for more info.
; Happy coding! ♥️

; Jacking in...
; Connecting using "deps.edn" project type.
; You can make Calva auto-select this.
;   - See https://calva.io/connect-sequences/
; 
; Starting Jack-in Terminal: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
; Using host:port localhost:44071 ...
; Hooking up nREPL sessions ...
; Failed connecting.
; Jack-in done.
clj꞉undefined꞉>  ; Use `alt+enter` to evaluate
```
Downgrading to 2.0.336 fixes the issue.

### PR DESCRIPTION
**Pull request by brancusi**
## What has changed?

- Adds a null check for cljsSession type that was in turn causing the connection to the nRepl session to fail sometimes.

Fixes #2113 - [Jack-in fails with version 2.0.337 ](https://github.com/BetterThanTomorrow/calva/issues/2113)

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/statusbar.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ function update(context = state.extensionContext) {
       typeStatus.text = ['cljc', config.REPL_FILE_EXT].includes(fileType)
         ? `cljc/${replType}`
         : replType;
-      if (cljSession.replType !== cljsSession.replType) {
+      if (cljSession.replType !== cljsSession?.replType) {
         typeStatus.command = 'calva.toggleCLJCSession';
```
Comment (PEZ) [inline src/statusbar.ts:96]: I've only heard of bugfixes this small in stories about progamming. 😄

**Review by PEZ — APPROVED** [review]
Thanks for the help with this, @brancusi! 🙏 ❤️
