### PR TITLE
Fix issue with wrong EOL val passed to LineInputModel on MS-Windows

### LINKED ISSUE #1994: Clojure notebooks don't seem to work on MS-Windows
Hi,

it appears that Clojure notebooks with MS-Windows CRLF line endings are broken, with sexp forms spilling over to the next code block:

image

How to reproduce.
1. Create a `dos.clj` file with CRLF endings in any project using the following code
``` clojure
(spit "dos.clj" "(ns dos\r\n  (:require [clojure.string :as str]))\r\n\r\n(str/split \"1 2\" #\" \")")
```
2. In VS Code Explorer right click on `doc.lj` and select `Open with...` -> `Clojure Notebook`.
3. You should get the above break in the first form whose last closing parenthesis spills over to the scond code cell.

PR to follow

### PR DESCRIPTION
**Pull request by ikappaki**
Hi 

could you please consider patch to account CRLF as two characters in the LineInputModel.

This is my first ever TS submission, so please scrutinize thoroughly as such.

## What has changed?

LineInputModel now receives as first argument the size of EOL seq in the text it is about to parse.

- It appears that LineInputModel accepts as first argument the number of characters in the EOL it parses. This default to 1, but on MS-Windows, the EOL length is two, so it is updated as such.

Fixes #1994

## My Calva PR Checklist

Hi, there are few points below which I couldn't figure out what you want me to do.

If this PR involves code changes, I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
~- [ ] Added to or updated docs in this branch, if appropriate~
- [ ] Tests
  - [x] Tested the particular change
  ~- [] Figured if the change might have some side effects and tested those as well.~
  - [ ] Smoke tested the extension as such. === I don't understand what you want me to do here. ===
 - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. ===  Not sure what you want me to do here ===
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-~keywords) === The link is broken when i copy pate it from the raw template. ===
~- [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

Thanks

### CODE REVIEW

File: src/cursor-doc/model.ts [hunk 1]
```diff
@@ -9,6 +9,17 @@ export function initScanner(maxLength: number) {
...
 
+/**
+ * @param text The text to look at for the line ending seq.
+ * @returns The first line ending sequence found in TEXT, if any.
+ */
+export function getFirstLineEndingSeq(text: string) {
+  const found = text.match(/\r\n|\n/g);
+  if (found) {
+    return found[0];
+  }
```
Comment (PEZ) [inline src/cursor-doc/model.ts]: I think it can be written as:
```suggestion
  return text.match(/\r\n|\n/g)?[0];
```
(I haven't tested 😄 )

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,8 @@ Changes to Calva.
 
 ## [Unreleased]
 
+- [Fix breakage with notebooks containing CRLF newlines on MS-Windows](https://github.com/BetterThanTomorrow/calva/issues/1994)
```
Comment (PEZ) [inline CHANGELOG.md]:
```suggestion
- Fix: [Breakage with notebooks containing CRLF newlines on MS-Windows](https://github.com/BetterThanTomorrow/calva/issues/1994)
```

This is the format we usually use for these.

File: src/cursor-doc/model.ts [hunk 3]
```diff
@@ -9,6 +9,17 @@ export function initScanner(maxLength: number) {
   scanner = new Scanner(maxLength);
 }
 
+/**
+ * @param text The text to look at for the line ending seq.
+ * @returns The first line ending sequence found in TEXT, if any.
+ */
+export function getFirstLineEndingSeq(text: string) {
```
Comment (PEZ) [inline src/cursor-doc/model.ts]: `LineEndingSeq` is called `eol` elsewhere in the codebase. Maybe `getFirstEol` is a good name for this function? Or just `firstEol`.

File: src/cursor-doc/model.ts [hunk 4]
```diff
@@ -527,14 +538,19 @@ export class LineInputModel implements EditableModel {
 
 export class StringDocument implements EditableDocument {
   constructor(contents?: string) {
+    let lineEndingSeq = null;
+    if (contents) {
+      lineEndingSeq = getFirstLineEndingSeq(contents);
+    }
```
Comment (PEZ) [inline src/cursor-doc/model.ts]: I tend to prefer `const` over `let`.

```suggestion
    const lineEndingSeq = contents ? getFirstLineEndingSeq(contents) : null;
```

I think @bpringe has showed me a way to write that more succinctly, but I don't recall the syntax right now. But maybe chatGPT knows. 😄

File: src/cursor-doc/token-cursor.ts [hunk 5]
```diff
@@ -943,7 +943,8 @@ export class LispTokenCursor extends TokenCursor {
  * Creates a `LispTokenCursor` for walking and manipulating the string `s`.
  */
 export function createStringCursor(s: string): LispTokenCursor {
-  const model = new LineInputModel();
+  const lineEndingSeq = getFirstLineEndingSeq(s);
+  const model = new LineInputModel(lineEndingSeq ? lineEndingSeq.length : 1);
```
Comment (PEZ) [inline src/cursor-doc/token-cursor.ts]: Looking at this I realize that this probably have been creating weird problems for Windows users for very long. Thanks!

File: src/extension-test/unit/cursor-doc/paredit-test.ts [hunk 6]
```diff
@@ -177,8 +177,7 @@ describe('paredit', () => {
         const b = docFromTextNotation('(a| b (c\r\n d)| e)');
         const [start, end] = textAndSelection(b)[1];
         const actual = paredit.forwardHybridSexpRange(a);
-        // off by 1 because \r\n is treated as 1 char?
-        expect(actual).toEqual([start, end - 1]);
```
Comment (PEZ) [inline src/extension-test/unit/cursor-doc/paredit-test.ts:181]: 🙏

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts [hunk 7]
```diff
@@ -28,6 +28,20 @@ describe('Token Cursor', () => {
...
+      cursor.forwardSexp();
+      expect(cursor.offsetStart).toBe(b.selection.anchor);
+    });
+    it('forwardSexp with newline (MS-Windows)', () => {
+      const a = docFromTextNotation('|(a\r\n(b))');
+      const b = docFromTextNotation('(a\r\n(b))|');
+      const cursor: LispTokenCursor = a.getTokenCursor(a.selection.anchor);
+      cursor.forwardSexp();
+      expect(cursor.offsetStart).toBe(b.selection.anchor);
+    });
```
Comment (PEZ) [inline src/extension-test/unit/cursor-doc/token-cursor-test.ts:44]: Thanks! Great to have this covered.

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts [hunk 8]
```diff
@@ -876,6 +890,18 @@ describe('Token Cursor', () => {
...
+        const cursor = createStringCursor('(a\n(b))');
+        const topLevelRanges = cursor.rangesForTopLevelForms().flat();
+        expect(topLevelRanges).toEqual([0, 7]);
+      });
+      it('Ranges account for newline (MS-Windows)', () => {
+        const cursor = createStringCursor('(a\r\n(b))');
+        const topLevelRanges = cursor.rangesForTopLevelForms().flat();
+        expect(topLevelRanges).toEqual([0, 8]);
+      });
+    });
```
Comment (PEZ) [inline src/extension-test/unit/cursor-doc/token-cursor-test.ts:904]: Awesome.

**Review by PEZ — CHANGES_REQUESTED** [review]
Thanks for doing this, @ikappaki! To me it looks like you have found the root cause and applied just the right fix. And great with the new tests and for claring up that strange mystery some of the existing tests. As I mention in some code comment, I think this must have been creating problems for Windows users before.

Thanks again! I have just a few nitpicks. Then we're good to go.

**Comment by PEZ** [comment]
> Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking Show all checks in the CI section of the PR page, and then Details on the ci/circleci: build test. === Not sure what you want me to do here ===

We usually leave that unchecked. We should clarify that it is for special cases when a change might behave differently in the release compiled code, and that this is rare.

File: src/cursor-doc/model.ts (hunk 1 above)
Comment (ikappaki) [reply src/cursor-doc/model.ts]: Updated, it appears it requires `?` to be followed by `.`

File: CHANGELOG.md (hunk 2 above)
Comment (ikappaki) [reply CHANGELOG.md]: Updated as suggested, but now using the title of the issue as link desc.

File: src/cursor-doc/model.ts (hunk 3 above)
Comment (ikappaki) [reply src/cursor-doc/model.ts]: I've changed all occurances of LineEndingSeq to Eol

File: src/cursor-doc/model.ts (hunk 4 above)
Comment (ikappaki) [reply src/cursor-doc/model.ts]: Updated.

File: src/cursor-doc/token-cursor.ts (hunk 5 above)
Comment (ikappaki) [reply src/cursor-doc/token-cursor.ts]: Hopefully I can do more testing in the future and discover these pesky windows bugs :)

File: src/extension-test/unit/cursor-doc/paredit-test.ts (hunk 6 above)
Comment (ikappaki) [reply src/extension-test/unit/cursor-doc/paredit-test.ts:181]: Thanks for confurming this was not intented :)

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts (hunk 7 above)
Comment (ikappaki) [reply src/extension-test/unit/cursor-doc/token-cursor-test.ts:44]: Thanks, this is the first thing I tried to reproduce as a test.

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts (hunk 8 above)
Comment (ikappaki) [reply src/extension-test/unit/cursor-doc/token-cursor-test.ts:904]: Yes this clearly shows that the windoes range has one more char

**Comment by ikappaki** [comment]
> > Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking Show all checks in the CI section of the PR page, and then Details on the ci/circleci: build test. === Not sure what you want me to do here ===
> 
> We usually leave that unchecked. We should clarify that it is for special cases when a change might behave differently in the release compiled code, and that this is rare.

I have refactored the code as suggested, if you could please have another look.

File: src/cursor-doc/token-cursor.ts (hunk 5 above)
Comment (PEZ) [reply src/cursor-doc/token-cursor.ts]: That would be great! We have been lacking someone who can focus on Windows issues a bit.

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts (hunk 7 above)
Comment (PEZ) [reply src/extension-test/unit/cursor-doc/token-cursor-test.ts:44]: We have an improved docFromTextNotation utility and some more goodies around it in a PR branch that has gone a bit stale. We should salvage that part of it.

File: package.json [hunk 9]
```diff
@@ -2881,7 +2881,7 @@
     "integration-test": "node ./out/extension-test/integration/runTests.js",
     "unit-test": "npx mocha --require ts-node/register 'src/extension-test/unit/**/*-test.ts'",
     "unit-test-watch": "npx mocha --watch --require ts-node/register --watch-extensions ts --watch-files src 'src/extension-test/unit/**/*-test.ts'",
-    "prettier-format": "npx prettier --write './**/*.{ts,js,json}'",
+    "prettier-format": "npx prettier --write \"./**/*.{ts,js,json}\"",
```
Comment (PEZ) [inline package.json]: Have you tested if this works on Mac and Linux? I can test that if you don't have a setup for it.

Comment (PEZ) [reply package.json]: I now tried it. Seems to work. Which is a bit surprising. Was the change needed on Windows?

**Review by PEZ — COMMENTED** [review]
Thanks again! I just have a question there about the double quotes for the prettier-format command.

File: package.json (hunk 9 above)
Comment (ikappaki) [reply package.json]: HI, yes, this and the watcher doesn't work under windows due to the single quotes, I reverted it for now since it went in prematurely. I plan to do a PR later on having tested all occurancies that need changing. 

It's good that you tested it to work on the other platforms. Thanks

Comment (PEZ) [reply package.json]: Thanks. It really seemed to work, but much better with a separate PR which can take a broader sweep on this kind of thing.

**Review by PEZ — APPROVED** [review]
LGTM. Thanks for providing!
