### PR TITLE
Fix range error

### LINKED ISSUE #2443: Calva Load File Command Results in RangeError on certain machine
When running "Calva: Load/Evaluate File" command in version 2.0.423 and beyond, I run into a RangeError:

```
; Evaluating file: dev.clj
; Evaluation of file dev.clj failed: RangeError: Maximum call stack size exceeded
```

I have tested this on multiple computers, but it only happens on my one machine. When I go back to version 422, it works as expected.

### PR DESCRIPTION
**Pull request by kurtharriger**
Fixes #2443 - 'RangeError: Maximum call stack size exceeded'

## What has changed?

- Removes stdout and stderr options are functions that can cause bencode to enter a loop 
https://clojurians.slack.com/archives/CBE668G4R/p1710811947262599

## My Calva PR Checklist

I have:

- [X] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [X] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [X] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [X] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [X] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [X] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [X] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
        - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [X] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [X] Added to or updated docs in this branch, if appropriate
- [ ] Tests
  - [X] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
- [X] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [X] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/nrepl/index.ts [hunk 1]
```diff
@@ -527,16 +527,17 @@ export class NReplSession {
     opts['pprint'] = pprintOptions.enabled;
     delete opts.pprintOptions;
     const extraOpts = getServerSidePrinter(pprintOptions);
+    const { stderr, stdout, ...optsLessOut } = opts;
```
Comment (PEZ) [inline src/nrepl/index.ts:530]: TIL!

**Comment by PEZ** [comment]
Sweet PR! Thanks for fixing this horrible bug. 🙏 ❤️   Was super hard for me to try track down, because I could never reproduce it.
