### PR TITLE
Wip/apply simple eslint rules

### LINKED ISSUE #1525: TS + ESLint upgrades
I'd like to upgrade typescript + eslint to be the latest and update the configuration for the latest. While initially I'd try to get it set up such that changes to existing code aren't required (or are minimal), I'd later like to introduce new eslint rules that improve the types across the app to prevent unexpected behaviors and add code clarity.

Sound good?

### LINKED ISSUE #1532: Apply some basic eslint rules to the project
After https://github.com/BetterThanTomorrow/calva/pull/1529 is applied, it would be great to apply some basic eslint rules and do the fixes for it.

### PR DESCRIPTION
**Pull request by corasaurus-hex**
## What has Changed?

This PR applies some basic eslint rules and provides the fixes to satisfy them. This is the step before applying the typescript eslint rules and performing the fixes for that, which will require deeper changes for it to work.

Requires #1529 to be merged before this.
Fixes #1532

I'll update the changelog once the pre-req PR is merged.

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [~] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) or run `npm run eslint`).

### CODE REVIEW

**Comment by corasaurus-hex** [comment]
Allllll ready for review @pez and @bpringe! #1529 needs to be merged first and this is the follow-up.

**Comment by Cyrik** [comment]
@corasaurus-hex I hope you get paid per line change 🥇 😄

**Comment by corasaurus-hex** [comment]
@Cyrik did you see this one? https://github.com/BetterThanTomorrow/calva/pull/1524 💀💀💀

File: src/cursor-doc/clojure-lexer.ts [hunk 1]
```diff
@@ -86,10 +88,10 @@ toplevel.terminal('lit-quoted-ws', /\\[\n\r\t ]/, (l, m) => ({ type: 'lit' }));
 toplevel.terminal('lit-quoted-chars', /\\.?/, (l, m) => ({ type: 'lit' }));
 toplevel.terminal(
     'lit-quoted',
-    /\\[^\(\)\[\]\{\}\s;,\\][^\(\)\[\]\{\}\s;,\\]+/,
+    /\\[^()[\]{}\s;,\\][^()[\]{}\s;,\\]+/,
```
Comment (PEZ) [inline src/cursor-doc/clojure-lexer.ts:91]: Does eslint find these?

File: src/connector.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ import { disabledPrettyPrinter } from './printer';
 import { keywordize } from './util/string';
 import { initializeDebugger } from './debugger/calva-debug';
 import * as outputWindow from './results-output/results-doc';
-import evaluate from './evaluate';
+import { evaluateInOutputWindow } from './evaluate';
```
Comment (PEZ) [inline src/connector.ts:19]: I prefer `import * as .. from` and thus to see from where something is called. We don't need to fix this now, just noting it for future discussions about code style.

File: src/cursor-doc/indent.ts [hunk 3]
```diff
@@ -83,7 +83,9 @@ export function collectIndents(
 
             const token = cursor.getToken().raw;
             const startIndent = cursor.rowCol[1];
-            if (!cursor.backwardUpList()) break;
+            if (!cursor.backwardUpList()) {
+                break;
+            }
```
Comment (PEZ) [inline src/cursor-doc/indent.ts:88]: 💪

File: src/nrepl/repl-start.ts [hunk 4]
```diff
@@ -139,16 +139,19 @@ async function extractBundledFiles(
...
                 path.join(context.extensionPath, TEMPLATES_SUB_DIR, docName)
             );
             try {
                 await vscode.workspace.fs.copy(templateUri, docUri, {
                     overwrite: true,
                 });
-            } catch {}
+            } catch {
+                // continue regardless of error
+            }
```
Comment (PEZ) [inline src/nrepl/repl-start.ts:154]: I like these. Will have to revisit and see if are missing some error handling here. The jack-in process is a bit flaky at times..

File: src/utilities.ts [hunk 5]
```diff
@@ -15,6 +15,7 @@ const syntaxQuoteSymbol = '`';
 
 export function stripAnsi(str: string) {
     return str.replace(
+        // eslint-disable-next-line no-control-regex
```
Comment (PEZ) [inline src/utilities.ts:18]: What does this mean?

**Review by PEZ — APPROVED** [review]
This is wonderful. Can't thank you enough for doing this, @corasaurus-hex ! ❤️

File: src/cursor-doc/clojure-lexer.ts (hunk 1 above)
Comment (corasaurus-hex) [reply src/cursor-doc/clojure-lexer.ts:91]: Yep! https://eslint.org/docs/rules/no-useless-escape

File: src/connector.ts (hunk 2 above)
Comment (corasaurus-hex) [reply src/connector.ts:19]: You can still use that, this just prevents you from calling a named export from a default export. https://github.com/import-js/eslint-plugin-import/blob/02ccbc1a30098822b7a6e7d84d8594b387495361/docs/rules/no-named-as-default-member.md

File: src/cursor-doc/indent.ts (hunk 3 above)
Comment (corasaurus-hex) [reply src/cursor-doc/indent.ts:88]: right? I love it!

File: src/nrepl/repl-start.ts (hunk 4 above)
Comment (corasaurus-hex) [reply src/nrepl/repl-start.ts:154]: Yeah, catching and not at least reporting it is usually a mistake. I didn't want to introduce new behavior though.

File: src/utilities.ts (hunk 5 above)
Comment (corasaurus-hex) [reply src/utilities.ts:18]: That disabled this eslint rule for the next line: https://eslint.org/docs/rules/no-control-regex#no-control-regex

Usually control characters in regex are a mistake but since we're stripping control characters here I'm disabling the rule just at this spot. this is the eslint escape hatch for when you really need it
