### PR TITLE
In clojure-lsp server downloader, use `platform` instead of `arch` to determine if running on Windows

### LINKED ISSUE #2287: Failing to download clojure-lsp server on Windows
I recently updated to the latest VSCode and now the clojure-lsp server won't start. This is the error the Calva extension is throwing:
```
Failed to download clojure-lsp server. Error: Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
```

These are the console logs in VSCode Developer Tools:
```
[Extension Host] Downloading clojure-lsp from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
[Extension Host] Clojure-lsp artifact downloaded to c:\Users\Jordan\.vscode\extensions\betterthantomorrow.calva-2.0.385\clojure-lsp-native-windows-amd64.zip
[Extension Host] Unzipping file
[Extension Host] Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip Error: ENOENT: no such file or directory, chmod 'c:\Users\Jordan\.vscode\extensions\betterthantomorrow.calva-2.0.385\clojure-lsp'
workbench.desktop.main.js:sourcemap:762 Failed to download clojure-lsp server. Error: Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
```

VSCode About dialog info:
```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

I have the latest Calva installed (`v2.0.385`). I also tried disabling all other extensions and only enabling Calva, and it still won't download.

### PR DESCRIPTION
**Pull request by JordanSkousen**
## What has changed?

- In the `getClojureLspPath` function in `src/lsp/client/downloader.ts`, the current code uses `process.arch` to determine if the OS is running on Windows. I've changed this to use `process.platform` instead. [Here's a StackOverflow](https://stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js?rq=4) that even says to use `process.platform` to determine the current operating system.

Fixes #2287

## My Calva PR Checklist

I have:

- [X] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [X] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [X] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [X] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [X] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [X] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [X] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [X] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
    - **Note**: I have tested this on the following operating systems:
         - Windows 11 Pro 10.0.22621
         - Windows 10 Home 10.0.19045
         - macOS Ventura 13.5
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [X] Tests
  - [X] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
- [X] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [X] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks for quickly contributing to fixing this! Great that you have tested three different machines.

File: src/lsp/client/downloader.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export function getClojureLspPath(
 ): string {
   let name = getArtifactDownloadName(platform, arch);
   if (path.extname(name).toLowerCase() !== '.jar') {
-    name = arch === 'win32' ? 'clojure-lsp.exe' : 'clojure-lsp';
+    name = platform === 'win32' ? 'clojure-lsp.exe' : 'clojure-lsp';
```
Comment (PEZ) [inline src/lsp/client/downloader.ts:39]: I'm thinking that since this has worked before, maybe we need to consider earlier versions of VS Code? Is it possible for you to try your fix with an earlier version of VS Code on the machine where you can reproduce the problem Previous versions can be found in the sidebar here: https://code.visualstudio.com/updates/v1_81

**Review by PEZ — COMMENTED** [review]
Very clean and targeted PR. 😄 I'm just a bit weary about if this could affect how things work on earlier VS Code versions. It's such an odd issue to suddenly appear, and you did mention that it seemed to start after an update of VS Code.

File: src/lsp/client/downloader.ts (hunk 1 above)
Comment (JordanSkousen) [reply src/lsp/client/downloader.ts:39]: Good idea. I have yet to find the root cause of the problem, I will do some more investigating as well as trying previous VS Code versions tomorrow!

**Comment by JordanSkousen** [comment]
I've discovered what caused the issue. It was introduced with this commit: 30d75e36ceab6369ad9296bf78e9e1daf90ff03a

The `getClojureLspPath()` function has always returned "clojure-lsp" instead of "clojure-lsp.exe" when running on Windows. Which means on Windows, line 145's `await fs.promises.chmod(clojureLspPath, 0o775);` has always thrown an error. The reason it's now a problem is because before that commit, the try/catch block would silently log the error and return `backupPath`. With this commit's change, it now throws an error, preventing the server from starting.

File: src/lsp/client/downloader.ts (hunk 1 above)
Comment (JordanSkousen) [reply src/lsp/client/downloader.ts:39]: I tested this on VS Code versions `1.78.2`, `1.79.2`, and `1.80.2`. It's all working 👍

**Comment by PEZ** [comment]
Ah, awesome that you found the root cause!

**Review by PEZ — APPROVED** [review]

**Comment by bpringe** [comment]
Thanks for the fix!
