### PR TITLE
[wip] Make the REPL work when using Live Share

### LINKED ISSUE #803: Live Share: sharing REPL port doesn't work
I'm using VSCode/Calva with Live Share a lot. According to the docs, you can share local network sockets over Live Share as well. We try to use this for Calva's REPL, so that the guest can also evaluate Clojure code in the host's REPL. When the guest tries to connect to this socket, using “connect to a running REPL”, I would expect to have to provide a port number, which doesn’t happen. Instead, in the VSCode “Log (Window)“, I see this error:

```
[2020-10-01 13:58:17.820] [renderer1] [error] Error: EROFS: read-only file system, mkdir '/.calva': Unknown (FileSystemError) (FileSystemError): Error: EROFS: read-only file system, mkdir '/.calva'
    at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:706:514)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

It seems like Calva doesn't detect that this folder is already present on the host. Please note that if `.calva` is in `.gitignore`, which it normally is of course, on the guest I don't even see the `.calva` folder and `output.calva-repl` buffer, so I guess the mechanism needs to take this into account.

### PR DESCRIPTION
**Pull request by svdo**
This pull request intends to fix using the REPL when using Live Share. After merging, users will be able to:

On the "host" side:

1. Open a project and jack-in
2. Start a live share session
3. Share the port used by the REPL

On the "guest" side:

1. Connect to the shared REPL port
2. Evaluate Clojure code the same way as when doing solo-development (<= this is the new part)

## What has Changed?
- The global state (`state.ts`) now not only has a `string` `getProjectRoot()` (which is the local file system reference), but also the `Uri` `getProjectRootUri()`, which is a Uri that can be local or remote.
- Finding, opening and processing the output window (`results-doc.ts`) uses the new `getProjectRootUri()` so that it works remotely as well as locally.
- When jacking in (i.e. on the host), in a live share scenario Calva offers to share the nREPL port automatically.

Closes #803.

## My Calva PR Checklist

I have:

- [X] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [X] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [X] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [X] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [X] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [X] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [X] Created the issue I am fixing/addressing, if it was not present.
- Check all references to `getProjectRoot()` and decide whether they can be changed to `getProjectRootUri()`
   - [x] `connector.ts:97`: `getFigwheelMainBuilds()` uses it to find files with name `.cljs.edn`
   - [x] `connector.ts:260`: `createCLJSReplType()` uses it to pass a file name to the quick picker
   - [x] `connector.ts:307`: `createCLJSReplType()` uses it to pass a file name to the quick picker
   - [x] `connectSequence.ts:226`: `askForConnectSequence()` uses it to figure out possible project kinds
   - [x] `jack-in.ts:52` and `jack-in.ts:56`: `executeJackInTask()` uses it to create a process execution environment for jacking in
   - [x] `project-types.ts:32`: `nreplPortFile()` uses it to read `.nrepl-port` for connecting to the right port
   - [x] `project-types.ts:44`: `shadowConfigFile()` uses it to return path to `shadow-cljs.edn`
   - [x] `project-types.ts:72`: `selectShadowBuilds()` uses it to pass a file name to the quick picker
   - [x] `project-types.ts:83`: `leinDefProject()` uses it to load `project.clj`
   - [x] `project-types.ts:115` and `project-types.ts:143`: `leinProfilesAndAlias()` uses it to pass a file name to the quick picker
   - [x] `project-types.ts:258`: `const projectTypes.clj.commandLine()` uses it to read `deps.edn`
   - [x] `project-types.ts:280`: `const projectTypes.clj.commandLine()` uses it to pass a file name to the quick picker
   - [x] `project-types.ts:436`: `detectProjectTypes()` uses it to check whether the user has access to the right project file
   - [X] `definition.ts:44`: has it in a comment about some future functionality, presumably
- [x] Investigate whether [`vsls`](https://www.npmjs.com/package/vsls) can be used to automatically setup the shared port and connect to it, instead of doing all that manually
- [x] Disable jack-in when connected as guest to a live share host (because you should _connect_, not _jack-in_)
- [x] Check whether the nrepl port to be used is automatically picked up by the guest
- [x] Disconnecting as a guest should not kill the REPL on the host, but only disconnect
- [ ] Write documentation page about using Calva with Live Share (including using `.vsls.json` to make `.calva` folder visible over live share)
- [ ] When using live share in read-only mode, the REPL port should not be shared.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by svdo** [comment]
@PEZ, @kstehn, @cfehse, @bpringe I think this PR is done. Please note that I did not update the package version number, I'm assuming I'm not supposed to do that in a PR. 

I have tested many different setups (CLJ, CLJS, fig wheel main, shadow-cljs, deps, lein) but the possible number of setups is larger than I'm able to test. But I'm not too worried given the nature of the changes that I made.

**Comment by PEZ** [comment]
This might be one of the best prepared PRs on Calva ever. I'll have a check and figure on how to test this.

File: src/connector.ts [hunk 1]
```diff
@@ -94,9 +102,11 @@ async function setUpCljsRepl(session, build) {
     namespace.updateREPLSessionType();
 }
 
-function getFigwheelMainBuilds() {
-    let res = fs.readdirSync(state.getProjectRoot());
-    let builds = res.filter(x => x.match(/\.cljs\.edn/)).map(x => x.replace(/\.cljs\.edn$/, ""));
+async function getFigwheelMainBuilds() {
+    let res = await vscode.workspace.fs.readDirectory(state.getProjectRootUri())
+    let builds = res
+        .filter(([name, type]) => type != vscode.FileType.Directory && name.match(/\.cljs\.edn/))
```
Comment (bpringe) [inline src/connector.ts:108]: This is a fairly minor thing, but it's good to use `!==` instead of `!=`. The `!=` and `==` are used elsewhere in the code in some places, but I like to keep new code using `!==` and `===`. This follows and airbnb style (which we want to follow with Calva as it's a pretty standard guide) here: https://github.com/airbnb/javascript#comparison-operators--equality, and reasoning is here: https://eslint.org/docs/rules/eqeqeq.html

File: src/connector.ts [hunk 2]
```diff
@@ -498,9 +512,15 @@ export default {
         status.update();
 
         if (nClient) {
-            // the connection may be ended before
-            // the REPL client was connected.
-            nClient.close();
+            if (state.getProjectRootUri().scheme == "vsls") {
```
Comment (bpringe) [inline src/connector.ts:515]: Another `==` to `===`. I hope this does not seem too picky :sweat_smile:

File: src/liveShareSupport.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
+import { Disposable } from 'vscode';
+import * as vsls from 'vsls';
+
+let liveShare: vsls.LiveShare = null;
+let liveShareListener: Disposable = null
+let connectedPort: number = null;
+let jackedIn = false
```
Comment (bpringe) [inline src/liveShareSupport.ts:7]: I think this stateful variable can be removed. I only see it being set, but never read, unless I'm missing something.

**Review by bpringe — CHANGES_REQUESTED** [review]
These changes are well-written. The only requests I have besides the one line comment are some style changes. Please forgive me for being the style police :smile:. Though not all of the existing code follows this style, we want to follow the styles mentioned in the wiki page [Coding Style](https://github.com/BetterThanTomorrow/calva/wiki/Coding-Style), which also links to the Airbnb style guide, which is pretty standard.

Two things I saw repeatedly in these changes:

- Use of `!=` and `==`, which should be replaced with `!==` and `===`, see https://github.com/airbnb/javascript#comparison--eqeqeq
- Missing semicolons, see https://github.com/airbnb/javascript#semicolons--required

Those links explain the reasons for doing it that way. It's small mostly inconsequential stuff, but helps avoid potential issues.

**Comment by svdo** [comment]
No worries Brandon, I agree that it's important. I'm just used to the opposite choices, that's all. (Semicolons are from the time that parsers were not smart enough to do without 😜) I'll fix these things. 

By the way I'm used in my own projects that VSCode fixes these things automatically (semicolons and string quotes at least, and warnings about ===), that hasn't been configured in the Calva project I guess?

**Comment by PEZ** [comment]
We should consider adding inter rules. It would fill the problem tab up, though, so that's why we have hesitated so far.

**Comment by bpringe** [comment]
Yeah, I agree that not having semicolons _probably_ wouldn't cause any issues, but it's a small thing to add. My brain seems to have a linter of its own in this regard :smile:. And for the sake of consistency :man_shrugging:.

I actually mentioned using a linter to Peter as well when making these comments. It would need to be a PR where we fix all code files or something, to get all the existing warnings out of the way.

**Comment by bpringe** [comment]
Added an issue for it: https://github.com/BetterThanTomorrow/calva/pull/805

**Comment by svdo** [comment]
> Added an issue for adding linting: #805

That should probably have been #816.

**Comment by svdo** [comment]
> Yeah, I agree that not having semicolons _probably_ wouldn't cause any issues, but it's a small thing to add. My brain seems to have a linter of its own in this regard 😄. And for the sake of consistency 🤷‍♂️.

Sure thing, consistency is nice.

File: src/liveShareSupport.ts (hunk 3 above)
Comment (svdo) [reply src/liveShareSupport.ts]: I added a comment in the code to clarify:

```typescript
// Keeps hold of the LiveShare API instance, so that it is requested only once.
let liveShare: vsls.LiveShare = null;

// Keeps hold of the LiveShare listener, to prevent it from being disposed immediately.
let liveShareListener: Disposable = null;
```

**Comment by svdo** [comment]
When working using a build of this PR today, I got this exception. Unfortunately the line numbers are incorrect, so I'm not sure what's going on:

```
[2020-10-12 09:25:40.561] [renderer3] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at /Users/stefan/.vscode/extensions/betterthantomorrow.calva-2.0.127-pull-805-a386a8dd/src/results-output/results-doc.ts:91:35
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:831:420
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at b.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:718:816)
    at b.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:716:848)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870:464)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870:156)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:868:817)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:867:623)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:865:691
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1059:179
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:451)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:489
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:851)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:203
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:54)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by bpringe** [comment]
>That should probably have been #816.

Whoops! Thanks.

About that error. I've seen it before, but maybe in another location/line. I seem to remember fixing it somewhere else. I think it's related to either a change event passing undefined as the editor, and/or in some cases the `activeTextEditor` is undefined. Likely this is not related to your changes though.

**Comment by svdo** [comment]
@bpringe @PEZ I think the PR is completely done now, including the coding style fixes and documentation page. Please let me know if you want anything else to be changed!

**Comment by bpringe** [comment]
Great documentation! Thanks for the coding style changes. I approve of this - I'll let @PEZ merge when he approves.

**Review by bpringe — APPROVED** [review]

**Comment by PEZ** [comment]
Awesome stuff. I agree with @bpringe  about those docs! I have this further feedback on them:

1. We generally do not mention in which version this or that feature entered. I can see how it could sometimes help to know this, but in the interest of keeping the docs on point, I'd say remove that.
2. Good to inform about the ignore of the `.calva` folder, but I think we should avoid hinting people on ignoring it entirely. It's `.calva/output-window/` that should be ignored for most projects. This is mentioned elsewhere in the docs.
3. I don't think we should introduce the docs menu changes in this PR. I see how the menu gets clearer, but it is a bigger issue involving SEO considerations and such. See attached image, which I think is not as good SEO as what is currently released.
4. I think LiveShare should be grouped together with WSL and Remote Dev in the menu.
5. This is good advice: _It may work better to evaluate things from your source code files instead of from the REPL window._ I just would want it to say ”_the_ source code editors” instead of ”your source code files”. (I started to think you where suggesting evaluating things locally instead, 😄 )

image

**Comment by svdo** [comment]
That's great feedback @PEZ, I agree with all of it. I'll update accordingly.

**Comment by svdo** [comment]
@PEZ I have made the changes. I changed the settings in `.vsls.json` a little bit, but unfortunately it doesn't seem to be possible to "unhide" _only_ the `.calva/output-window` folder, so I'm afraid this is the best we can do for now.

**Comment by PEZ** [comment]
Thanks a lot for this work, @svdo !  I've been wanting to be able to say that Calva works with LoveShare for so long now.

**Comment by svdo** [comment]
You're very welcome @PEZ, and thanks for the supportive way of handling my questions and contribution!

**Comment by PEZ** [comment]
This is now out! https://clojurians.slack.com/archives/C06MAR553/p1602927186218200 🎉
