### PR TITLE
Fix warning when error loading file

### LINKED ISSUE #1567: Warning when loading a file produces an error: n.filter is not a function
To reproduce, while connected to a repl, put a symbol at the top level of the file that's not defined (like `a`, assuming that is not defined) and load the file. See the warning:

image

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Accesses the stacktrace array on an nrepl eval result correctly (before it was just accessing the stacktrace object, but not the array within it, which caused an error when another function called .filter on what it expected to be an array)
- Removes appending of the prompt from `printLastStacktrace` in favor of leaving the responsibility up to the caller and removing a responsibility from the function that isn't related to its main task. (This follows the single responsibility principle.)

Fixes #1567 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
     - [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe

### CODE REVIEW

File: src/evaluate.ts [hunk 1]
```diff
@@ -436,7 +436,7 @@ async function loadFile(
     } catch (e) {
       outputWindow.append(`; Evaluation of file ${fileName} failed: ${e}`);
       if (res.stacktrace) {
-        outputWindow.saveStacktrace(res.stacktrace);
+        outputWindow.saveStacktrace(res.stacktrace.stacktrace);
```
Comment (bpringe) [inline src/evaluate.ts:439]: The first stacktrace is an object, which contains a stacktrace property, which refers to an array.

File: src/extension.ts [hunk 2]
```diff
@@ -229,11 +229,8 @@ async function activate(context: vscode.ExtensionContext) {
     vscode.commands.registerCommand('calva.selectCurrentForm', select.selectCurrentForm)
   );
   context.subscriptions.push(
-    vscode.commands.registerCommand('calva.loadFile', async () => {
-      await eval.loadFile({}, config.getConfig().prettyPrintingOptions);
-      return new Promise((finished) => {
-        outputWindow.appendPrompt(finished);
-      });
```
Comment (bpringe) [inline src/extension.ts:236]: The prompt is already appended when the file is loaded, so there's no need to do it here, which actually causes it to be printed twice.

**Comment by bpringe** [comment]
@PEZ The stacktrace is printed in the output window when an error occurs when loading the file. Is that expected/intended? (Normally, stacktraces are not printed on error, but are saved for printing later if desired.)

**Comment by bpringe** [comment]
@Cyrik Any idea why that test is failing? I tested jacking in and loading a file manually and it seems to work fine. It looks like maybe the file loading part of the test isn't run by the time it makes its assertion.

File: src/extension.ts [hunk 3]
```diff
@@ -231,9 +231,7 @@ async function activate(context: vscode.ExtensionContext) {
   context.subscriptions.push(
     vscode.commands.registerCommand('calva.loadFile', async () => {
       await eval.loadFile({}, config.getConfig().prettyPrintingOptions);
-      return new Promise((finished) => {
-        outputWindow.appendPrompt(finished);
-      });
+      outputWindow.appendPrompt();
```
Comment (PEZ) [inline src/extension.ts]: Could this be the reason the integration tests are now flaky?

**Comment by PEZ** [comment]
I also wonder what goes wrong with the integration test. The test results:

```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

[
  '',
  'clj꞉test꞉> ',
  'nil',
  'bar',
  '; Evaluating file: test.clj'
]

should loosely deep-equal

[
  '',
  'clj꞉user꞉> ',
  '; Jack-in done.',
  'clj꞉user꞉>  ; Use `alt+enter` to evaluate',
  ';   - Clojure lines in stack traces are peekable and clickable.'
]
```


(We could consider not running a `reverse()` on the array before testing to make it a bit easier to map in your head to what s printed.)

Anyway. Running the integration tests locally I get:

```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

[
  '',
  'clj꞉test꞉> ',
  'nil',
  'bar',
  '; Evaluating file: test.clj'
]

should loosely deep-equal

[
  '',
  '; Evaluating file: test.clj',
  'clj꞉user꞉> ',
  '; Jack-in done.',
  'clj꞉user꞉>  ; Use `alt+enter` to evaluate'
]
```

Which seems to indicate that it is a bit arbitrary when we read the results. But it used to not be flaky here, so probably something in the PR changes. I've commented on a change I suspect.

File: src/extension.ts (hunk 3 above)
Comment (bpringe) [reply src/extension.ts]: I don't think this change itself really produced a behavioral change, but I could be wrong. If it did though, maybe we should update the test, as I the behavior seems to be what's desired.

Comment (bpringe) [reply src/extension.ts]: The Promise there is unnecessary, but I can add it back and try the tests again when I have time.

Comment (Cyrik) [reply src/extension.ts]: I don't think we should keep a promise just to make the test happy 😄 
But I think the promise might be useful outside the test as well. If you don't return that promise here, there is no way to wait for the file load + output window update to be done.

**Comment by Cyrik** [comment]
@PEZ Yeah the missing promise means that we'll check the repl output before it has been written to.
The way I do the checks isn't ideal I think, but it feels like it's the closest thing to really checking what the user experiences.

File: src/extension.ts (hunk 3 above)
Comment (PEZ) [reply src/extension.ts]: I agree about the value of being able to wait for the window updates to be done.

Disagree about not keeping the promise for testing purposes only. 😄

Comment (PEZ) [reply src/extension.ts]: How about:

```typescript
      // We use this promise in the E2E tests
      return new Promise((finished) => {
         outputWindow.appendPrompt(finished);
       });
```

Comment (Cyrik) [reply src/extension.ts]: I meant that I usually dislike having code that only exists for testing purposes. This promise is currently only used in tests, but it does make general sense for it to exist anyway. If I had a feature that wants to load a file and wait for that to be done, that promise is actually important. 
So I'm in favor of keeping it without the extra comment 😄

Comment (PEZ) [reply src/extension.ts]: And I meant that I usually like having code that exists only for testing. 😄 Testability is one of those altars I am ready to bring sacrifice to.

Comment (bpringe) [reply src/extension.ts:234]: > I don't think we should keep a promise just to make the test happy

I wasn't suggesting that - I just wanted to test and see if it was affecting the test for some reason.

The function inherently returns a promise since it's async, and if you await it, the promise is resolved after the `await loadFile` execution completes. There's no need to return a separate promise like that.

Comment (bpringe) [reply src/extension.ts]: Wow, somehow I missed that the promise was actually being resolved after the prompt was appended in the output window 😑 . I added it back as I agree it could be useful besides just for testing.
