### PR TITLE
Use array instead of object for indent rules

### LINKED ISSUE #2284: Can't override default cljfmt config since 2.0.383
Example:
Trying to override the default let-rule doesn't work.

### PR DESCRIPTION
**Pull request by juiceghost**
## What has changed?

- Use array instead of object for indent rules. The earlier method of spreading objects and then combining them overwrote existing keys in the provided configuration.

* Fixes #2284 

## My Calva PR Checklist

I have:

- [X] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [X] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [X] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [X] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [X] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [X] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [X] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [X] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [X] Tests
  - [X] Tested the particular change
  - [X] Figured if the change might have some side effects and tested those as well.
- [X] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [X] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Review by PEZ — APPROVED** [review]
Thanks for helping to improve Calva! 🙏 

I learnt that I had it totally wrong about how spreads of objects work.

File: src/cursor-doc/indent.ts [hunk 1]
```diff
@@ -63,7 +63,12 @@ export function collectIndents(
   let lastLine = cursor.line;
   let lastIndent = 0;
   const indents: IndentInformation[] = [];
-  const rules = { ...config['cljfmt-options']['indents'], ...cljsLib.defaultIndents() };
+  const defaultIndents = cljsLib.defaultIndents();
+  const extraIndents = config['cljfmt-options']['indents'];
+  const defaultRules = Object.keys(defaultIndents).map((k) => [k, defaultIndents[k]]);
+  const extraRules = Object.keys(extraIndents).map((k) => [k, extraIndents[k]]);
+  const rules = [...extraRules, ...defaultRules];
```
Comment (bpringe) [inline src/cursor-doc/indent.ts:70]: Could we not have just reversed the spread?

```typescript
const rules = { ...cljsLib.defaultIndents(), ...config['cljfmt-options']['indents'], };
```

Maybe I'm missing the core problem though. It seems that the user-provided indents should override the default where they intersect.
