### PR TITLE
Don't move on the last coor for atoms

### LINKED ISSUE #2501: Throws error when debugging atoms
The problem arises when debugging a function using an atom. In this particular case the atom is declared within a let binding.
In order to reproduce the issue:

0. Clone this [repo](https://github.com/javierrweiss/calva-debugger-issues):
1. Use "Instrument top level form for debugging" command.
2. Then either use the "Step over" or "Step out" commands.
3. Finally, in this particular reproduction case it will throw the error when evaluating the swap! function.

### PR DESCRIPTION
**Pull request by PEZ**
## What has changed?

For atoms (or any ref) the debugger will expand the `@...` syntax sugar to `(deref ...)` giving us an extra `coor` in debug response. Now we just go to the next `coor` value when we see that we're at a sexpr starting with `@`.

* Fixes #2501

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~~[ ] Added to or updated docs in this branch, if appropriate~~
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/debugger/util.ts [hunk 1]
```diff
@@ -28,9 +28,7 @@ function moveTokenCursorToBreakpoint(
   const coor = [...debugResponse.coor]; // Copy the array so we do not modify the one stored in state
 
   for (let i = 0; i < coor.length; i++) {
-    while (!tokenCursor.downListSkippingMeta()) {
-      tokenCursor.next();
-    }
+    tokenCursor.downListSkippingMeta();
```
Comment (PEZ) [inline src/debugger/util.ts:31]: @bpringe I don't know why this wasn't just downList, so changed it to that, because I don't actually understand the while loop. And it seldom is a good idea to move non-structurally like it does inside there. OTOH, I am thinking there is a reason, so that's why tagging you here. 😄

File: src/extension-test/unit/debugger/util-test.ts [hunk 2]
```diff
@@ -17,63 +16,119 @@ function getCoordinates(text: string): (string | number)[] {
...
+      // TODO: Figure out why this test fails.
+      // It works interactively.
+      // And the coor given to us from cider-nrepl is really [3, 1]
+      xit('deref call', () => {
+        expectBreakpointToBeFound(`;; 3, 1
+        #dbg
+        (defn boom
+          []
+          @(f)|)`);
+      });
```
Comment (PEZ) [inline src/extension-test/unit/debugger/util-test.ts:131]: I don't understand why this test fails. Do you, @jpmonettas?

Comment (jpmonettas) [reply src/extension-test/unit/debugger/util-test.ts:131]: Sorry, no idea, I never wrote Calva tests , not sure how that pipe thing is supposed to work

Comment (PEZ) [reply src/extension-test/unit/debugger/util-test.ts:131]: The pipe is placing the document cursor. And these tests start the text with the `coor`. When I run this interactively with the repl message log on I can see that the cursor is exactly there when the debugger shows the ref value and that it has responded with `(3, 1)` coor.

But still a bit unfair to expect you to shed light on this, since it probably is just me having misunderstood something. 😄  Will experiment a bit more with it.

Comment (PEZ) [reply src/extension-test/unit/debugger/util-test.ts:131]: If you're curious about the test mechanics, have a look at the rest of the tests in this file and it'll probably clear up a bit.

Comment (jpmonettas) [reply src/extension-test/unit/debugger/util-test.ts:131]: What about the test we were doing before with `@a` instead of `@(f)` ?

Comment (PEZ) [reply src/extension-test/unit/debugger/util-test.ts:131]: Ah, thanks. That's a typo. Now fixed. It worked because I think it is interpreted as a selection and the default is that the cursor is at the end of the selection from left to right.

File: src/extension-test/unit/debugger/util-test.ts [hunk 3]
```diff
@@ -17,63 +16,119 @@ function getCoordinates(text: string): (string | number)[] {
...
+    });
+
+    describe('derefs', () => {
+      it('atom', () => {
+        expectBreakpointToBeFound(`;; 3, 1
+        #dbg
+        (defn boom
+          []
+          @!a|)`);
+      });
```
Comment (PEZ) [inline src/extension-test/unit/debugger/util-test.ts:110]: @jpmonettas , I now realize you may be referring to this test. It passes just fine.

File: src/debugger/util.ts (hunk 1 above)
Comment (bpringe) [reply src/debugger/util.ts:31]: It's been too long for me to remember the reason that was like that 😄. However, if the existing tests pass, then we can be somewhat confident this change doesn't break anything.
