### PR TITLE
Stop indenting vectors using indent rules meant for lists

### LINKED ISSUE #1622: Indenting not working correctly in vectors starting with fn-like symbols
If I have the below code and press enter with my cursor where noted with `|` in the first example, it then ends up where noted in the second.

Starting:

```clj
(let [context {:a 1
               :b [{:c 2}]}|])
```

When I press enter:

```clj
(let [context {:a 1
               :b [{:c 2}]}
       |])
```

What I expect after pressing enter:

```clj
(let [context {:a 1
               :b [{:c 2}]}
      |])
```

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

#1622 reports a bug with our indent engine (not to be confused with our formatter) where vectors maps have a symbol in ”call”. position produces indents as if the vector was a list. So we get:

``` clojure
[do|]
```

<kbd>enter</kbd>

``` clojure
[do
  |]
```

Instead of 

``` clojure
[do
 |]
```

I've added some unit tests for the indenter. Some of which expose the bug. And now all those are green.

Fixes #1622

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [ ] Tests
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
I found a clean (imo) way to fix the issue. Please have a look and check that you agree.

File: src/cursor-doc/indent.ts [hunk 1]
```diff
@@ -84,11 +89,8 @@ export function collectIndents(
         break;
       }
 
-      const rules = config['cljfmt-options']['indents'];
-      const pattern = _.find(
-        _.keys(rules),
-        (pattern) => pattern == token || testCljRe(pattern, token)
-      );
+      const pattern =
+        isList && _.find(_.keys(rules), (pattern) => pattern == token || testCljRe(pattern, token));
```
Comment (bpringe) [inline src/cursor-doc/indent.ts]:
```suggestion
        isList && _.find(_.keys(rules), (pattern) => pattern === token || testCljRe(pattern, token));
```

**Review by bpringe — APPROVED** [review]
Did a loose review, and considering you've got good test coverage too, it looks good to me!

**Comment by PEZ** [comment]
Thanks, @bpringe! 🙏
