### PR TITLE
Some VIM co-existence fixes

### LINKED ISSUE #1947: Make Calva a bit more VIM friendly
User of the VIM extension often run into troubles with some incompatibilities with Calva. Specifically these two issues are reported:

* The cursor jumps to the beginning of the line when entering new lines
* The `escape` key is bound to dismiss inline results

Users get rid of the issue with the cursor positioning by configuring Calva to not use the ”New indent engine”. I have been thinking this is a matter of the old engine being slower and thus being later than the VIM extension to the party. But today I realized that another difference is that the old indent engine actively sets the cursor position after re-indenting. So maybe we can do the same with the new indenter and solve this issue...

The `escape` key problem could be made much less impactful if we only bind it when we are actually showing inline results.

### PR DESCRIPTION
**Pull request by PEZ**
## What has changed?

* Introduce a context state for when inline results are displayed or not
* Using the new context state to only bind `escape` when inline results are showing
* Explicitly set the new cursor position after re-indenting with the new indent engine
* Some bug fixes with how we make sure the new indent engine gets a clean slate to start from

In my testing, the explicit cursor positioning fixes the problem with the cursor ending up at the start of te line when the VIM extension is enabled. 

Fixes #1947

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [ ] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
  - [x] Smoke tested the extension as such.
  - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

File: src/calva-fmt/src/extension.ts [hunk 1]
```diff
@@ -82,4 +79,9 @@ export async function activate(context: vscode.ExtensionContext) {
     )
   );
   vscode.window.onDidChangeActiveTextEditor(inferer.updateState);
+  vscode.workspace.onDidChangeConfiguration((e) => {
+    if (e.affectsConfiguration('calva.fmt.formatAsYouType')) {
```
Comment (bpringe) [inline src/calva-fmt/src/extension.ts:83]: Isn't this setting removed now?

Comment (PEZ) [reply src/calva-fmt/src/extension.ts:83]: Might be a merge thing that I missed... I vaguely remember something with a strange merge when doing something recently.
