### PR TITLE
Fix bug with clojure lsp format config race condition

### LINKED ISSUE #1561: Format config from clojure-lsp broken
The format on save works when I save a file, but apparently, the format doesn't correspond to the `clojure-lsp` config. Also, an error is showing when a open my project.

versions:
```
calva v2.0.245
clojure-lsp version used: 2022.02.23-12.12.12
clj-kondo version used: 2022.02.09
```
settings:
```
"calva.fmt.configPath": "CLOJURE-LSP",
"calva.clojureLspPath": "/usr/local/bin/clojure-lsp",
"editor.formatOnSave": true,
```
error:
```
Fetching formatting settings from clojure-lsp failed. Check that you are running a version of clojure-lsp that provides "cljfmt-raw" in serverInfo.
```

Running the Clojure-lsp Server Info I see the `cljfmt-raw` field.
```
  "cljfmt-raw": "{:indents {assoc-in-some [[:block 1] [:block 1] [:block 1] [:block 1]], facts [[:block 1] [:block 1] [:block 1] [:block 1]], with-responses [[:block 0] [:block 0] [:block 0] [:block 0]], provided [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], as-delegate [[:block 2] [:block 2] [:block 2] [:block 2]], lambda-expr [[:inner 0]], |fn [[:inner 0]], assoc-if [[:block 1] [:block 1] [:block 1] [:block 1]], defglobal-native [[:inner 0]], profile [[:block 2] [:block 2] [:block 2] [:block 2]], with-scopes [[:block 1] [:block 1] [:block 1] [:block 1]], consume! [[:block 0] [:block 0] [:block 0] [:block 0]], defint [[:block 0] [:block 0] [:block 0] [:block 0]], as-delegate-with-lift [[:block 2] [:block 2] [:block 2] [:block 2]], defglobal-library [[:inner 0]], |if-not [[:block 1]], |when [[:block 1]], let-entities [[:block 2] [:block 2] [:block 2] [:block 2]], |with-state [[:block 1]], constraint-fn [[:block 2] [:block 2] [:block 2] [:block 2]], as-customer [[:block 1] [:block 1] [:block 1] [:block 1]], for-all [[:block 1] [:block 1] [:block 1] [:block 1]], flow [[:block 1] [:block 1] [:block 1] [:block 1]], against-background [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], quick-check [[:block 1] [:block 1] [:block 1] [:block 1]], against-backgroud [[:block 0]], logged-call [[:block 1] [:block 1] [:block 1] [:block 1]], run-recipe [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], log-messages [[:block 0] [:block 0] [:block 0] [:block 0]], profiled [[:block 1] [:block 1] [:block 1] [:block 1]], |def-expr [[:inner 0]], as-admin [[:block 1] [:block 1] [:block 1] [:block 1]], try-type [[:block 0] [:block 0] [:block 0] [:block 0]], |if [[:block 1]], future-facts [[:block 1] [:block 1] [:block 1] [:block 1]], some-with-open [[:block 1] [:block 1] [:block 1] [:block 1]], not-join [[:block 1]], fact [[:block 1] [:block 1] [:block 1] [:block 1]], expand-routes [[:inner 1] [:inner 1] [:inner 1] [:inner 1]], flow-with-defaults [[:block 1] [:block 1] [:block 1]], if-expr [[:block 1]], |let [[:block 1]], idempotent-start [[:block 1] [:block 1] [:block 1] [:block 1]], idempotent-stop [[:block 1] [:block 1] [:block 1] [:block 1]], as-of [[:block 1] [:block 1] [:block 1] [:block 1]], with-fn-validation [[:block 0] [:block 0] [:block 0] [:block 0]], defuf [[:block 1] [:block 1] [:block 1] [:block 1]], rethrow [[:block 1] [:block 1] [:block 1] [:block 1]], flow-as-of [[:block 1] [:block 1] [:block 1] [:block 1]], assoc-some [[:block 1] [:block 1] [:block 1] [:block 1]], future-fact [[:block 1] [:block 1] [:block 1] [:block 1]], tabular [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], as-customer-with-lift [[:block 1] [:block 1] [:block 1] [:block 1]], non-test-action [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], data-fn [[:block 1] [:block 1] [:block 1] [:block 1]], let-expr [[:block 1]], assoc [[:block 1] [:block 1] [:block 1] [:block 1]], assoc-in-if [[:block 1] [:block 1] [:block 1] [:block 1]], flow-without-validation [[:block 1] [:block 1] [:block 1] [:block 1]], ignore-conflict [[:inner 0] [:inner 0] [:inner 0] [:inner 0]], with-cid [[:block 1] [:block 1] [:block 1] [:block 1]], let-flow [[:block 1] [:block 1] [:block 1] [:block 1]], embeds [[:block 0] [:block 0] [:block 0] [:block 0]], system-map [[:block 0] [:block 0] [:block 0] [:block 0]], defhandler [[:block 2] [:block 2] [:block 2] [:block 2]]}}"
 ```

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

The new feature with fetching cljfmt config from clojure-lsp was a bit too naïvely implemented. It worked when I tested it while developing, but of course the order in witch things initialize is not reliable like that...

I've now added a function in lsp/main.ts that lets's you await the lsp client before you query it. It's a bit brute, I think, but it does the job, afaikt. Might come in handy for other things.

I've also made the `startClient` function abort if the client fails to start. Less "Promise reject was not handled” messages in the console.

Can you have a look at the changes, @bpringe ? I'm always a bit confused around promises. 😄 

I'm a bit worried that formatting operations will now hang if the CLOJURE-LSP option is used and clojure-lsp takes time to initialize....

Also, @corasaurus-hex : I know you removed some async/await constructs because they weren't needed. Here I am introducing such things again. If you see an opportunity for me to learn a bit about this, please go ahead. 😄 

Fixes #1561

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [ ] Tests
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [ ] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe

### CODE REVIEW

File: src/calva-fmt/src/config.ts [hunk 1]
```diff
@@ -55,10 +72,6 @@ function readConfiguration() {
     }
 }
 
-export function setLspFormatConfig(config: string) {
-    lspFormatConfig = config;
-}
-
 export function getConfig() {
     const config = readConfiguration();
     return config;
```
Comment (isacjunior) [inline src/calva-fmt/src/config.ts]: Suggestion: As the `readConfiguration` return a promise, we need to await the config here, right?
```suggestion
export async function getConfig() {
    const config = await readConfiguration();
    return config;
```

Comment (PEZ) [reply src/calva-fmt/src/config.ts]: Yes, maybe that is better than sprinkling all those awaits around like I have done. Thanks!

File: src/calva-fmt/src/config.ts [hunk 2]
```diff
@@ -26,9 +27,25 @@ function configuration(
...
+    if (configPath === LSP_CONFIG_KEY && !lspFormatConfigFetched) {
+        lspFormatConfig = await lsp
+            .getCljFmtConfig()
+            .then((c) => {
+                lspFormatConfigFetched = true;
+                return c;
+            })
+            .catch((e) => {
+                lspFormatConfigFetched = true;
+            });
```
Comment (isacjunior) [inline src/calva-fmt/src/config.ts]: **🎯  Suggestion:** Maybe a `try catch` here is easier to read.‏

```suggestion
      try {
        lspFormatConfig = await lsp.getCljFmtConfig(); 
        lspFormatConfigFetched = true;
      } catch (_) {
        lspFormatConfigFetched = true;
      }
```

Comment (PEZ) [reply src/calva-fmt/src/config.ts]: 🙏

File: src/lsp/main.ts [hunk 3]
```diff
@@ -430,15 +430,20 @@ async function startClient(
     lspStatus.text = '$(rocket) clojure-lsp';
     lspStatus.show();
     client.start();
-    await onReadyPromise;
+    await onReadyPromise.catch((e) => {
+        console.error('clojure-lsp:', e);
+        setStateValue(LSP_CLIENT_KEY_ERROR, e);
+    });
```
Comment (corasaurus-hex) [inline src/lsp/main.ts:436]: it's funny, before I worked on this project I didn't know you could mix `await` + `.catch`

File: src/lsp/main.ts [hunk 4]
```diff
@@ -658,6 +663,33 @@ export async function getClojuredocs(
     }
 }
 
+// TODO: This feels a bit brute, what are other ways to wait for the client to initialize?
```
Comment (corasaurus-hex) [inline src/lsp/main.ts:666]: This is fine as-is but we could pull in a package for this -- like https://github.com/devlato/async-wait-until -- to get something with behavior that's easier to wrap your head around.

**Comment by corasaurus-hex** [comment]
@PEZ this all looks great, and eslint agrees! 😉

It's fine to add back in async/await when it's needed, and eslint/typescript will complain when it is/isn't needed, so you're good.

**Comment by PEZ** [comment]
Thanks. Very good to know.

While working with this I introduced some bugs by not awaiting the promise at some places. Is there a way eslint can be made to help with that?

**Comment by corasaurus-hex** [comment]
It already should be, I thought?

**Comment by corasaurus-hex** [comment]
Whoops, it wasn't turned on, but the PR that just linked to this turns it on.

File: src/calva-fmt/src/config.ts [hunk 5]
```diff
@@ -55,11 +69,7 @@ function readConfiguration() {
     }
 }
 
-export function setLspFormatConfig(config: string) {
-    lspFormatConfig = config;
-}
-
-export function getConfig() {
-    const config = readConfiguration();
+export async function getConfig() {
```
Comment (bpringe) [inline src/calva-fmt/src/config.ts:72]: This function is actually redundant. You can just export `readConfiguration` and await it where you call it, which is the same as awaiting a call to this function.

File: src/cljs-lib/src/calva/fmt/formatter.cljs [hunk 6]
```diff
@@ -286,17 +286,19 @@
   [^js m]
   (-> m
       (parse-cljfmt-options-string)
+      (update-in [:config :cljfmt-options] merge-cljfmt)
       (format-text)))
 
 (defn format-text-at-range-bridge
   [^js m]
+  (def m m)
```
Comment (bpringe) [inline src/cljs-lib/src/calva/fmt/formatter.cljs:294]: Left one of these in 😄 .

File: src/lsp/main.ts (hunk 3 above)
Comment (bpringe) [reply src/lsp/main.ts:436]: I didn't know this either 😄 .

File: src/lsp/main.ts (hunk 4 above)
Comment (bpringe) [reply src/lsp/main.ts:666]: @PEZ If you return `onReadyPromise` from `startClient` you can just await `startClient` to know when the client has started and is ready, rather than using this `getClient` function. I could help with that if you want.

File: src/cljs-lib/src/calva/fmt/formatter.cljs (hunk 6 above)
Comment (PEZ) [reply src/cljs-lib/src/calva/fmt/formatter.cljs:294]: Whoopsie! We should probably clean the ClojureScript code up to where it has zero warnings and check it in CI.

File: src/lsp/main.ts (hunk 4 above)
Comment (PEZ) [reply src/lsp/main.ts:666]: Oh, that would be less brute. I'll have a go at it and see where it brings me. Thanks!

Comment (bpringe) [reply src/lsp/main.ts:666]: No problem! You may want to put the code that was previously after the await within `startClient` inside a .then.

So it would be like

```typescript
return onReadyPomise.then(_ => { ...do-stuff });
```

That should return the promise as well as run the code we want to run after the client starts.

Comment (bpringe) [reply src/lsp/main.ts:666]: Also there may be a better way to do the above... but the above is a simple refactor.
