### PR TITLE
Fix code navigation fail after starting repl

### LINKED ISSUE #2804: Code navigation fail after starting repl
We can see where a function is called from by cmd(ctrl)+left-clicking the function name at its definition, and we can also jump to its definition by cmd(ctrl)+left-clicking on the function name where it's called. However, after starting repl, the latter still works while the former doesn't anymore. Exiting repl restores it.

### PR DESCRIPTION
**Pull request by jramosg**
## What has changed?

- Updated the provideClojureDefinition function to check if the resolved URI matches the current document's URI. If they match, it delegates to the lspDefinition function for further processing.
- Updated the provideClojureDefinition and provideDefinition methods to include a cancellation token parameter.

Fixes #2804

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

### CODE REVIEW

File: src/providers/definition.ts [hunk 1]
```diff
@@ -28,7 +31,11 @@ async function provideClojureDefinition(
       if (info.file && info.file.length > 0) {
         const pos = new vscode.Position(info.line - 1, info.column || 0);
         try {
-          return new vscode.Location(vscode.Uri.parse(info.file, true), pos);
+          const uri = vscode.Uri.parse(info.file, true);
+          if (uri.toString() === document.uri.toString()) {
+            return lspDefinition(clientProvider, document, position, token);
```
Comment (PEZ) [inline src/providers/definition.ts]: It seems wrong to provide lsp definition in the function that is mapped to providing repl definitions?

If this is a fallback, then that fallback should probably happen in provideDefinitions?

Comment (jramosg) [reply src/providers/definition.ts]: you're right, ClojureDefinitionProvider already handles the fallback
```ts
 async provideDefinition(document, position: vscode.Position, token: vscode.CancellationToken) {
    const providers = config.getConfig().definitionProviderPriority;
    for (const provider of providers) {
      const providerFunction = definitionFunctions[provider];
      if (providerFunction) {
...
```

**Comment by PEZ** [comment]
This looks good to me now. Is it ready to merge, from your perspective, @jramosg ?

**Comment by jramosg** [comment]
I've been using this build yesterday afternoon and today morning I didn't see anything strange and code navegation was fixed, so yes!
