### PR TITLE
Fix: Evaluating `#_` prefixed forms

### LINKED ISSUE #3144: Option-Return at the end of an expression prefixed with #_ is no longer triggering evaluation
This happens because of https://github.com/BetterThanTomorrow/calva/pull/3114

### PR DESCRIPTION
**Pull request by jramosg**
## What has changed?

- Strip the #_ reader discard prefix from code text in `evaluateSelection()` before sending to the REPL

Fixes #3144 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

### CODE REVIEW

**Comment by PEZ** [comment]
> I did not create the issue, expeting lspector (clojurians slack) to create it. If not I can create it

It's surprisingly common that people don't file an issue, even when we ask for it. I don't think it's worth waiting. 😀

**Comment by jramosg** [comment]
haha, I just create it :smile:

File: src/evaluate.ts [hunk 1]
```diff
@@ -333,6 +333,11 @@ async function evaluateSelection(document = {}, options) {
     let code = selection[1];
     [codeSelection, code]; //TODO: What's this doing here?
 
+    // Strip leading #_ and optional whitespace so that
+    // evaluating with the cursor at the end of #_(form) sends just (form)
+    // to the REPL instead of the silently-discarded #_(form).
+    code = code.replace(/^#_\s*/, '');
```
Comment (PEZ) [inline src/evaluate.ts]: I think we shouldn't strip `#_` if there is a selection. Like it could be:

```clojure
|#_(breakage) 42|
```

And that should evaluate to 42, not crash.

But if nothing is selected, it should be fine to strip.

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,8 @@ Changes to Calva.
 
 ## [Unreleased]
 
+- Fix: [Evaluating `#_`-prefixed forms](https://github.com/BetterThanTomorrow/calva/issues/3144)
```
Comment (PEZ) [inline CHANGELOG.md]:
```suggestion
- Fix: [Option-Return at the end of an expression prefixed with #_ is no longer triggering evaluation](https://github.com/BetterThanTomorrow/calva/issues/3144)
```

Comment (PEZ) [reply CHANGELOG.md]: Rationale: Good issue titles (like the one you wrote) describe the problem. The Changelog is a log of problems solved.
