### PR TITLE
Always add ws roots to project root candidates

### LINKED ISSUE #1613: Connect fails when there is no project file (`deps.edn`, etc)
I have a custom project type in `.vscode/settings.json`:

```json
{
    "calva.replConnectSequences": [
        {
            "name": "Monorepo REPL",
            "projectType": "generic",
            "nReplPortFile": [".nrepl-port"],
            "afterCLJReplJackInCode": "(start)",
            "cljsType": "none"
        }
    ]
}
```

In 2.0.256, I can connect a REPL client.

In 2.0.257, I 
1. Start my REPL server
2. Run `Calva: Connect to a running REPL Server`
3. I'm greeted with the new `Project root` picker
4. I bypass with <kbd>Esc</kbd>
5. I'm greeted with `Please select a project type`
6. I choose `Monorepo REPL`
7. A popup appears with message `Failed initializing project root directory:`

I think this was introduced by #1254.

### PR DESCRIPTION
**Pull request by PEZ**
This restores the ability to connect/jack-in to projects that have no project files. Which is the case with many Babashka projects.

Fixes #1613

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [ ] Tests
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @Cyrik , @corasaurus-hex

### CODE REVIEW

File: src/project-root.ts [hunk 1]
```diff
@@ -4,14 +4,26 @@ import * as config from './config';
 import * as path from 'path';
 
 export async function findProjectRootPaths() {
-  const projectFileNames: string[] = ['project.clj', 'shadow-cljs.edn', 'deps.edn'];
+  const projectFileNames: string[] = [
+    'project.clj',
+    'shadow-cljs.edn',
+    'deps.edn',
+    'bb.edn',
+    '.nrepl-port',
```
Comment (brettrowberry) [inline src/project-root.ts:12]: Yes!
