### PR TITLE
Assorted Paredit quality fixes

### LINKED ISSUE #1098: Paredit slurp sometimes leaves an extra space
I think the moved paren might be replaced by a space:

```clojure
(s|tr )#(foo)'
```

<kbd>slurp</kbd>

**Expected**

```clojure
(s|tr #(foo))
```

**Actual**

```clojure
(s|tr  #(foo))
```

### PR DESCRIPTION
**Pull request by PEZ**
- [x] [Replace extra whitespace with one when slurping](https://github.com/BetterThanTomorrow/calva/issues/1098)
- [x] [Delete empty literal function causes newline to be removed ](https://github.com/BetterThanTomorrow/calva/issues/1079)
- [x] Add experimental setting to: [Prevent extra closing brackets in strict mode](https://github.com/BetterThanTomorrow/calva/issues/650)

Fixes #1098

There are some serious changes in paredit `backspace` and also generally. I've added tests to guard against the regressions I could think up.

My testing says that the `backspace` changes should be for the better. Deleting an extraneous closing bracket now doesn't require force-backspace.

For the prevention of adding unbalanced closing brackets this applies:

> Adding a setting to prevent inserting unbalanced closing brackets. As it isn’t really possible to do this in VS Code, it is a bit clumsy, the bracket is added (since we can’t stop it), then removed, then only added if there is unbalance in the document. The rational being that if there is unbalance, all bets are off, the human at the keyboard is best suited to heal it. The solution doesn’t behave well when it is a selection that is replaced with the closing bracket, so don’t do that if you have this setting enabled.

(And with the backspace fixes even leaving this setting disabled should not be as painful as it used to be.)

TODO:

- [x] Give `delete` the same love as `backspace` has gotten.
- [x] Document the new setting

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)

Ping @bpringe

### CODE REVIEW

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts [hunk 1]
```diff
@@ -76,11 +77,26 @@ describe('Token Cursor', () => {
...
         });
 
+        xit('Does not move past unbalanced top level form', () => {
+            //TODO: Figure out why this doesn't work
+            const d = docFromTextNotation('|(foo "bar"');
+            const cursor: LispTokenCursor = d.getTokenCursor(d.selectionLeft);
+            cursor.forwardSexp();
+            expect(cursor.offsetStart).toBe(d.selectionLeft);
+        });
+        xit('Does not move past unbalanced top level form', () => {
```
Comment (PEZ) [inline src/extension-test/unit/cursor-doc/token-cursor-test.ts:87]: @bpringe, this is the test that breaks coming tests. Something runs amok when there is no closing quote. But the way it runds amok!

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts [hunk 2]
```diff
@@ -76,11 +77,26 @@ describe('Token Cursor', () => {
             expect(cursor.offsetStart).toBe(14);
         });
 
+        xit('Does not move past unbalanced top level form', () => {
+            //TODO: Figure out why this doesn't work
```
Comment (PEZ) [inline src/extension-test/unit/cursor-doc/token-cursor-test.ts:81]: This is utterly strange. It actually does work in the vscode editor, but not like this. I suspect it might have to do with the ”runs amok@ thing, since also here we have a missing close. But that is just a wild guess.

File: src/extension-test/unit/cursor-doc/token-cursor-test.ts (hunk 1 above)
Comment (bpringe) [reply src/extension-test/unit/cursor-doc/token-cursor-test.ts:87]: Weird, so, maybe something to do with the `"` after `bar`, whereas the one above doesn't have that? No clue what it could be though.
