### PR TITLE
Ensure clojure-lsp starts reliably when offline or on restricted networks

### LINKED ISSUE #1299: Clojure-lsp not starting when offline
When my Mac is offline (or I’m on a corporate VPN) and I open a Clojure project in VS Code with Calva, the Clojure-lsp server doesn’t start and thus all LSP-powered functionality is unavailable. `Calva Diagnostics : Clojure-lsp Server Info` says "There is no clojure-lsp server running." The welcome message from Calva looks as usual, there’s no visible indication of an error.

As soon as I re-connect to wi-fi (or disconnect from the corporate VPN) and restart VS Code, Clojure-lsp starts as expected. I was able to reproduce this issue both on my work and personal laptops.

Note: I do realize that by default Calva downloads the latest version of Clojure-lsp, but I always assumed it would re-use the latest available download if offline.

### PR DESCRIPTION
**Pull request by marco-carvalho**
## What has changed?

- Added a 10-second timeout to the GitHub API version check in `getLatestVersion()`, preventing indefinite hangs when offline or behind restrictive firewalls/VPNs.
- Added a 120-second socket timeout to `downloadArtifact()`, preventing stalled downloads from blocking server startup forever.
- After a failed download, the backup binary is now restored to its original canonical location instead of being left in the `backup/` directory. This ensures subsequent offline startups can find and reuse the previously downloaded binary.
- Extracted the backup/restore logic into `downloader-utils.ts` to enable unit testing without VS Code dependencies.
- Backup file is cleaned up after a successful download to avoid stale backups accumulating.

Fixes #1299

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~Added to or updated docs in this branch, if appropriate~
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks! This is awesome! Changes so far look good to me. Let us know when it's ready from your POV.

File: src/lsp/client/downloader-utils.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+export async function downloadWithBackupRecovery(
+  filePath: string,
+  download: () => Promise<void>
+): Promise<{
+  path: string;
+  restored: boolean;
+}> {
+  const backupPath = await backupFile(filePath);
+  try {
+    await download();
```
Comment (jramosg) [inline src/lsp/client/downloader-utils.ts:40]: shouldn't we clean up backup directory after succesful download? It is left on disk indefinitely and over many update cycles, stale backups are accumulated

```ts
 if (backupPath) {
    await fs.promises.unlink(backupPath).catch(() => {});
  }
```

File: src/lsp/client/downloader-utils.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    return { path: filePath, restored: false };
+  } catch (e) {
+    if (!backupPath) {
+      throw e;
+    }
+    const restored = await restoreFile(backupPath, filePath);
```
Comment (jramosg) [inline src/lsp/client/downloader-utils.ts:50]: The logs were removed from `downloadClojureLsp`
Maybe we should maintain the log here?

```ts
 console.log('Download failed, recovering from backup:', e.message)
```

**Comment by marco-carvalho** [comment]
Thanks @jramosg for the review! Both points addressed:

1. Backup file is now cleaned up after a successful download (`unlink`), so stale backups don't accumulate across updates.
2. Added `console.log('Download failed, recovering from backup:', e.message)` in the recovery path to maintain visibility.

Also added a test assertion that verifies the backup cleanup after success.

Thanks @PEZ, this is ready from my side!

**Comment by jramosg** [comment]
You're missing Calva PR Checklist and therefore to update changelog :pray:

**Comment by marco-carvalho** [comment]
Done, thanks @jramosg!

**Comment by PEZ** [comment]
Thanks, both of ya! 🙏

**Comment by bpringe** [comment]
Great work! Thanks!
