### PR TITLE
885 fstat await problem

### LINKED ISSUE #885: Jack-in prompt never showing on some Windows machines
On my Virtual Box Windows machine, jack-in doesn't work since we added the Live Share changes. The cause is that the way we use `vscode.workspace.fs.stat(uri)` is not the way it is [recommended by the VS Code team](https://github.com/microsoft/vscode-extension-samples/blob/master/fsconsumer-sample/src/extension.ts).

This doesn't seem to affect non-Windows users, and also I see no reports of it causing problems to any Windows users either. Except me then.

The code where this is happening is fundamental, so when it hits it will cause a lot of things in Calva to stop working.

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?
Fix jack-in prompt never appearing on Windows.

Doesn't seem to happen to users out there, but on my Windows machine jack-in doesn't work.

The fix is to wrap the `fs.stat()` call in a try/catch instead of using the return value. Quite strange, but it is how the [VS Code team is recommending it to be done](https://github.com/microsoft/vscode-extension-samples/blob/master/fsconsumer-sample/src/extension.ts). (And also, it does fix the problem.)

Fixes #885

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Created the issue I am fixing/addressing, if it was not present.
- ~[ ] Added to or updated docs in this branch, if appropriate~

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by PEZ** [comment]
I added you as a reviewer just so that you can look at the change, @bpringe . You don't need interrupt your workflow with those other changes to test this out, I have tested it quite extensively. But if the changes look good to you, please merge the PR. =)

**Comment by kstehn** [comment]
actually i had some problems with jack-in.
but not with every project but some and i didnt knew why.
So i couldnt write repro-steps for this.

But back to topic:
i tested the vsix for my problem projects and they work now correctly :)

**Comment by PEZ** [comment]
Oh, then we should hurry to get this out. The error behaviour is so silent. Very strange that it only his some projects, but life is full of mysteries, I guess. 😎

Thanks for sharing the info!

File: src/state.ts [hunk 1]
```diff
@@ -253,17 +253,18 @@ async function findProjectRootUri(projectFileNames, doc, workspaceFolder): Promi
...
+                try {
+                    await vscode.workspace.fs.stat(u);
                     cursor.set(PROJECT_DIR_URI_KEY, searchUri);
                     return;
                 }
+                catch { }
             }
-            catch (_) { }
         }
+        catch (_) { }
```
Comment (bpringe) [inline src/state.ts:267]: Should we log something useful here in case we have an issue later, so we can easily find the source?

**Review by bpringe — CHANGES_REQUESTED** [review]
Looks good to me, just had a minor request/comment.

File: src/state.ts (hunk 1 above)
Comment (PEZ) [reply src/state.ts:267]: Yes we should. Good catch!

**Comment by PEZ** [comment]
I added the logging. Merging this now.
